// SPDX-License-Identifier: MIT

/* liblor in a single-header.
   Generated by tools/gen_single_header.py; do not edit by hand. */

#ifndef LOR_SINGLE_HEADER_H
#define LOR_SINGLE_HEADER_H
#define LOR_SINGLE_HEADER_BUILD

/* Module selection
   If no LOR_ENABLE_* macro is defined, every stable module is enabled.
   Define one or more LOR_ENABLE_* macros before including this header
   to include only those modules. */
#if !defined(LOR_ENABLE_STATUS) && !defined(LOR_ENABLE_MEMORY) && !defined(LOR_ENABLE_STRING)
#define LOR_ENABLE_ALL
#endif

#ifdef LOR_ENABLE_ALL
#define LOR_ENABLE_STATUS
#define LOR_ENABLE_MEMORY
#define LOR_ENABLE_STRING
#endif

#if defined(LOR_LEAKCHECK)
#define LOR_ENABLE_MEMORY
#endif

#ifdef LOR_ENABLE_STRING
#define LOR_ENABLE_STATUS
#endif

// === status: declarations ===
#ifdef LOR_ENABLE_STATUS
#ifdef __cplusplus
extern "C" {
#endif

typedef enum LorStatus {
    LOR_STATUS_OK = 0,
    LOR_STATUS_INVALID_ARGUMENT,
    LOR_STATUS_OUT_OF_MEMORY,
    LOR_STATUS_OVERFLOW
} LorStatus;

// Returns a stable lowercase name for `status`, or "unknown".
const char *lor_status_name(LorStatus status);

#ifdef __cplusplus
}
#endif
#endif

// === memory: declarations ===
#ifdef LOR_ENABLE_MEMORY
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LOR_KIB(n) ((size_t)(n) << 10)
#define LOR_MIB(n) ((size_t)(n) << 20)
#define LOR_GIB(n) ((size_t)(n) << 30)

#define LOR_ARENA_DEFAULT_BLOCK_SIZE LOR_KIB(64)
#define LOR_ARENA_DEFAULT_RESERVE_SIZE LOR_MIB(64)
#define LOR_ARENA_DEFAULT_COMMIT_SIZE LOR_KIB(64)

typedef enum {
    LOR_ARENA_BACKEND_HEAP = 0,
    LOR_ARENA_BACKEND_VIRTUAL = 1
} LorArenaBackend;

typedef struct LorArenaBlock LorArenaBlock;

typedef struct LorArenaConfig {
    // Selects which backing storage the arena uses.
    LorArenaBackend backend;
    // Preferred usable capacity of each heap block. Ignored when virtual.
    size_t block_size;
    // Preferred address-space reservation per virtual block. Ignored when heap.
    size_t reserve_size;
    // Virtual-memory commit granularity. Ignored when heap.
    size_t commit_size;
} LorArenaConfig;

typedef struct LorArena {
    // Blocks owned by the arena, newest first. Shared by both backends.
    LorArenaBlock *blocks;
    // Determines how blocks are acquired, grown, and released.
    LorArenaBackend backend;
    // Preferred heap block capacity. Ignored by the virtual backend.
    size_t block_size;
    // Preferred virtual block reservation. Ignored by the heap backend.
    size_t reserve_size;
    // Virtual-memory commit granularity. Ignored by the heap backend.
    size_t commit_size;
} LorArena;

typedef struct LorArenaMark {
    // Block that was active when the mark was taken.
    LorArenaBlock *block;
    // Used offset in `block` when the mark was taken.
    size_t used;
} LorArenaMark;

typedef struct LorScratch {
    LorArena *arena;
    LorArenaMark mark;
} LorScratch;

#define LOR_ARENA_INIT {NULL, LOR_ARENA_BACKEND_HEAP, 0u, 0u, 0u}
#define LOR_ARENA_MARK_INIT {NULL, 0u}
#define LOR_SCRATCH_INIT {NULL, LOR_ARENA_MARK_INIT}

/* Initializes `arena` with the default heap-backed configuration.

   Passing `NULL` fails and returns zero. A zero-initialized arena can also be
   used lazily by calling `lor_arena_alloc` without an explicit init call. */
int lor_arena_init(LorArena *arena);

/* Initializes `arena` with explicit configuration.

   Fields left as zero use the same defaults as `lor_arena_init`. Use
   `LOR_ARENA_BACKEND_VIRTUAL` to reserve virtual memory and commit it on demand. */
int lor_arena_init_config(LorArena *arena, LorArenaConfig config);

/* Releases all storage owned by `arena` and resets it to `LOR_ARENA_INIT`.

   Passing `NULL` is a no-op. All pointers previously allocated from the arena
   become invalid. */
void lor_arena_deinit(LorArena *arena);

/* Rewinds all allocations in `arena` while keeping its allocated blocks.

   Passing `NULL` is a no-op. This retains the arena's high-water storage for
   reuse; call `lor_arena_deinit` to release storage back to the system. */
void lor_arena_reset(LorArena *arena);

/* Returns a checkpoint for temporary allocations inside `arena`.

   The mark is a plain value and should be passed back to `lor_arena_rewind`
   with the same arena. Passing `NULL` returns `LOR_ARENA_MARK_INIT`. */
LorArenaMark lor_arena_mark(const LorArena *arena);

/* Rewinds `arena` to `mark`.

   Blocks allocated after a non-empty mark are released. A zero mark rewinds all
   allocations while retaining allocated blocks. Passing `NULL` is a no-op.
   Marks must come from the same arena. */
void lor_arena_rewind(LorArena *arena, LorArenaMark mark);

/* Allocates `size` bytes from `arena`.

   Returns `NULL` when `arena` is `NULL`, `size` is zero, or backing allocation
   fails. The returned pointer is owned by the arena and must not be freed
   individually. */
void *lor_arena_alloc(LorArena *arena, size_t size);

// Allocates zero-filled `size` bytes from `arena`.
void *lor_arena_alloc_zero(LorArena *arena, size_t size);

/* Allocates `count * elem_size` bytes from `arena`.

   Returns `NULL` for zero counts, zero element sizes, or size overflow. */
void *lor_arena_alloc_array(LorArena *arena, size_t count, size_t elem_size);

// Allocates a zero-filled array from `arena`.
void *lor_arena_alloc_array_zero(LorArena *arena, size_t count, size_t elem_size);

/* Copies the NUL-terminated string `text` into `arena`.

   Returns the arena-owned copy, or `NULL` when `text` is `NULL` or allocation
   fails. */
char *lor_arena_strdup(LorArena *arena, const char *text);

/* Returns the usable capacity currently consumed in `arena`.

   The result includes alignment padding between allocations, so it can exceed
   the sum of requested allocation sizes. Resetting or rewinding lowers this
   value without necessarily lowering capacity or committed memory. Passing
   `NULL` returns zero. */
size_t lor_arena_used(const LorArena *arena);

/* Returns the total usable capacity currently held by `arena`.

   Block metadata and alignment slack are excluded. For heap arenas every byte
   of capacity is backed by an allocation, so this equals
   `lor_arena_committed`. For virtual arenas this is reserved usable
   address-space capacity and can be larger than committed memory. Passing
   `NULL` returns zero. */
size_t lor_arena_capacity(const LorArena *arena);

/* Returns the usable capacity currently backed by committed memory.

   Block metadata and alignment slack are excluded. This equals
   `lor_arena_capacity` for heap arenas. For virtual arenas it grows on demand
   in commit-size increments and is not reduced by reset or rewind within a
   retained block. Passing `NULL` returns zero. */
size_t lor_arena_committed(const LorArena *arena);

/* Begins a scratch scope and returns a handle for a thread-local scratch arena.

   The memory module automatically provisions 2 pre-initialized thread-local arenas 
   for you to use without any manual setup. 

   `conflicts` may name arenas whose live allocations must not be overwritten by
   the new scratch scope. This is specifically needed when a nested helper 
   requires temporary memory but must output its final results to one of the
   calling scope's active arenas.

   Returns `LOR_SCRATCH_INIT` when no scratch arena is available or initialization fails. */
LorScratch lor_scratch_begin(LorArena **conflicts, size_t conflict_count);

/* Ends a scratch scope and rewinds its borrowed arena.

   Passing an inactive handle is a no-op. */
void lor_scratch_end(LorScratch scratch);

// Releases all initialized scratch arenas for the current thread.
void lor_scratch_cleanup(void);

// Returns the host operating system page size, or a conservative fallback.
size_t lor_page_size(void);

typedef enum LorMmapMode {
    // Read-only mapping. Writes through `data` are invalid.
    LOR_MMAP_READ = 0,
    // Writable private copy. Changes are not written to the file.
    LOR_MMAP_COPY = 1,
    // Writable shared mapping. Changes are visible in the mapped file.
    LOR_MMAP_SHARED = 2
} LorMmapMode;

typedef struct LorMmap {
    void *data;
    size_t size;
} LorMmap;

/* Maps the file at `path` using `mode`.

   Returns `{0}` when `path` is `NULL`, the file cannot be opened, the file is
   empty or too large, `mode` is invalid, or the mapping fails. Successful
   mappings must be released with `lor_mmap_unmap`. */
LorMmap lor_mmap_file(const char *path, LorMmapMode mode);

/* Unmaps `map` and resets it to `{0}`.

   Passing `NULL` or an already-unmapped value is a no-op. */
void lor_mmap_unmap(LorMmap *map);

typedef struct LorLeakStats {
    size_t heap_count;
    size_t heap_bytes;
    size_t arena_count;
    size_t mmap_count;
    size_t mmap_bytes;
} LorLeakStats;

/* Returns current leakcheck counters.

   In normal builds, all counters are zero. Leakcheck tracking is process-global
   and not synchronized; use it from one thread or protect calls externally. */
LorLeakStats lor_leakcheck_stats(void);

/* Returns the number of currently tracked leakcheck records.

   In normal builds, this returns zero. */
size_t lor_leakcheck_count(void);

/* Writes current leakcheck records to `out` and returns the number written.

   Passing `out == NULL` writes to `stderr`. In normal builds, this writes
   nothing and returns zero. */
size_t lor_leakcheck_report(FILE *out);

#if defined(LOR_LEAKCHECK)
// Leakcheck wrapper for `malloc` with explicit source location metadata.
void *lor_malloc_debug(size_t size, const char *file, int line);

// Leakcheck wrapper for `calloc` with explicit source location metadata.
void *lor_calloc_debug(size_t count, size_t elem_size, const char *file, int line);

// Leakcheck wrapper for `realloc` with explicit source location metadata.
void *lor_realloc_debug(void *ptr, size_t size, const char *file, int line);

// Leakcheck wrapper for `free` with explicit source location metadata.
void lor_free_debug(void *ptr, const char *file, int line);

// Leakcheck wrapper for `strdup` with explicit source location metadata.
char *lor_strdup_debug(const char *text, const char *file, int line);

// Leakcheck-tracked form of `lor_arena_init` with explicit source location.
int lor_arena_init_debug(LorArena *arena, const char *file, int line);

// Leakcheck-tracked form of `lor_arena_init_config`.
int lor_arena_init_config_debug(LorArena *arena, LorArenaConfig config,
                                const char *file, int line);

/* Leakcheck-tracked form of `lor_arena_alloc`.

   Arena allocations are still bulk-owned by the arena; this location is used
   only when a zero-initialized arena is lazily initialized by the allocation. */
void *lor_arena_alloc_debug(LorArena *arena, size_t size, const char *file,
                            int line);

// Leakcheck-tracked form of `lor_arena_alloc_zero`.
void *lor_arena_alloc_zero_debug(LorArena *arena, size_t size, const char *file,
                                 int line);

// Leakcheck-tracked form of `lor_arena_alloc_array`.
void *lor_arena_alloc_array_debug(LorArena *arena, size_t count, size_t elem_size,
                                  const char *file, int line);

// Leakcheck-tracked form of `lor_arena_alloc_array_zero`.
void *lor_arena_alloc_array_zero_debug(LorArena *arena, size_t count,
                                       size_t elem_size, const char *file, int line);

// Leakcheck-tracked form of `lor_arena_strdup` with explicit source location.
char *lor_arena_strdup_debug(LorArena *arena, const char *text, const char *file,
                             int line);

// Leakcheck-tracked form of `lor_mmap_file` with explicit source location.
LorMmap lor_mmap_file_debug(const char *path, LorMmapMode mode, const char *file,
                            int line);
#endif

/* Scope cleanup has to be a macro because C attributes are declaration syntax.
   Unsupported compilers leave LOR_AUTO_* empty, so code remains portable. */
#if defined(__GNUC__) || defined(__clang__)
#define LOR_CLEANUP_SUPPORTED 1
#define LOR_CLEANUP(fn) __attribute__((cleanup(fn)))
#define LOR_MAYBE_UNUSED __attribute__((unused))
#else
#define LOR_CLEANUP_SUPPORTED 0
#define LOR_CLEANUP(fn)
#define LOR_MAYBE_UNUSED
#endif

static inline void LOR_MAYBE_UNUSED lor_memory_cleanup_free_(void *ptr) {
    void **value = (void **)ptr;
    if (value == NULL || *value == NULL) return;
#if defined(LOR_LEAKCHECK)
    lor_free_debug(*value, NULL, 0);
#else
    free(*value);
#endif
    *value = NULL;
}

static inline void LOR_MAYBE_UNUSED lor_memory_cleanup_arena_(void *arena) {
    lor_arena_deinit((LorArena *)arena);
}

static inline void LOR_MAYBE_UNUSED lor_memory_cleanup_scratch_(void *scratch) {
    LorScratch *value = (LorScratch *)scratch;
    if (value == NULL || value->arena == NULL) return;
    lor_scratch_end(*value);
    *value = (LorScratch)LOR_SCRATCH_INIT;
}

static inline void LOR_MAYBE_UNUSED lor_memory_cleanup_mmap_(void *map) {
    lor_mmap_unmap((LorMmap *)map);
}

static inline void LOR_MAYBE_UNUSED lor_memory_cleanup_file_(void *file) {
    FILE **value = (FILE **)file;
    if (value == NULL || *value == NULL) return;
    (void)fclose(*value);
    *value = NULL;
}

#define LOR_AUTO_FREE LOR_CLEANUP(lor_memory_cleanup_free_)
#define LOR_AUTO_ARENA LOR_CLEANUP(lor_memory_cleanup_arena_)
#define LOR_AUTO_SCRATCH LOR_CLEANUP(lor_memory_cleanup_scratch_)
#define LOR_AUTO_MMAP LOR_CLEANUP(lor_memory_cleanup_mmap_)
#define LOR_AUTO_FILE LOR_CLEANUP(lor_memory_cleanup_file_)

#ifdef __cplusplus
}
#endif
#endif

// === string: declarations ===
#ifdef LOR_ENABLE_STRING
#include <stddef.h>
#include <stdio.h>


#ifdef __cplusplus
extern "C" {
#endif

/* Borrowed byte string.

   A view does not own `data`, does not require a NUL terminator, and remains
   valid only while the referenced bytes remain valid and unmoved. `data` may
   be `NULL` only when `size` is zero. */
typedef struct LorStringView {
    const char *data;
    size_t size;
} LorStringView;

#define LOR_STRING_VIEW_INIT {NULL, 0u}
#define LOR_SV_LITERAL(text) {(text), sizeof(text) - 1u}

// Creates a view over `size` bytes. Invalid `NULL`/non-zero input returns empty.
LorStringView lor_sv_from_parts(const char *data, size_t size);

// Creates a view over a NUL-terminated C string. Passing `NULL` returns empty.
LorStringView lor_sv_from_cstr(const char *text);

// Returns non-zero when the view satisfies its pointer/size invariant.
int lor_sv_is_valid(LorStringView view);

// Returns non-zero when `view` contains no bytes.
int lor_sv_is_empty(LorStringView view);

// Compares the complete binary contents of two views.
int lor_sv_equal(LorStringView a, LorStringView b);

// Returns whether `view` begins with `prefix`.
int lor_sv_starts_with(LorStringView view, LorStringView prefix);

// Returns whether `view` ends with `suffix`.
int lor_sv_ends_with(LorStringView view, LorStringView suffix);

// Removes ASCII whitespace from the left side of `view`.
LorStringView lor_sv_trim_left(LorStringView view);

// Removes ASCII whitespace from the right side of `view`.
LorStringView lor_sv_trim_right(LorStringView view);

// Removes ASCII whitespace from both sides of `view`.
LorStringView lor_sv_trim(LorStringView view);

/* Returns at most `size` bytes starting at `offset`.

   Out-of-range offsets and sizes are clamped to the view bounds. */
LorStringView lor_sv_slice(LorStringView view, size_t offset, size_t size);

// Returns at most the first `size` bytes of `view`.
LorStringView lor_sv_take_left(LorStringView view, size_t size);

// Returns at most the last `size` bytes of `view`.
LorStringView lor_sv_take_right(LorStringView view, size_t size);

// Removes and returns at most the first `size` bytes from `view`.
LorStringView lor_sv_chop_left(LorStringView *view, size_t size);

// Removes and returns at most the last `size` bytes from `view`.
LorStringView lor_sv_chop_right(LorStringView *view, size_t size);

/* Finds `needle` and writes its byte offset to `index`.

   An empty needle is found at offset zero. `index` is unchanged on failure. */
int lor_sv_find(LorStringView view, LorStringView needle, size_t *index);

// Finds `needle` and writes its byte offset to `index`.
int lor_sv_find_char(LorStringView view, char needle, size_t *index);

/* Splits `view` around the first non-empty `delimiter`.

   On success, writes the bytes before and after the delimiter and returns
   non-zero. When not found, writes `view` to `before`, an empty view to
   `after`, and returns zero. */
int lor_sv_split_once(LorStringView view, LorStringView delimiter,
                      LorStringView *before, LorStringView *after);

// Character-delimiter form of `lor_sv_split_once`.
int lor_sv_split_once_char(LorStringView view, char delimiter,
                           LorStringView *before, LorStringView *after);

/* Removes the next delimiter-separated part from `view`.

   When the delimiter is found, consumes it and returns non-zero. Otherwise,
   returns the remaining input as `part`, empties `view`, and returns zero.
   An empty or invalid delimiter leaves `view` unchanged. */
int lor_sv_chop(LorStringView *view, LorStringView delimiter,
                LorStringView *part);

// Character-delimiter form of `lor_sv_chop`.
int lor_sv_chop_char(LorStringView *view, char delimiter, LorStringView *part);

/* Writes exactly `view.size` bytes to `out` without adding a newline.

   Returns non-zero when the complete view was written. Unlike `%s` and
   `%.*s`, this preserves embedded NUL bytes and supports lengths above
   `INT_MAX`. */
int lor_sv_fprint(FILE *out, LorStringView view);

// Writes `view` to stdout using `lor_sv_fprint`.
int lor_sv_print(LorStringView view);

/* Owned, mutable byte string.

   The handle points directly to NUL-terminated content and can be indexed or
   passed to read-only C string APIs when non-NULL. Size and capacity metadata
   are stored in a private allocation header. Do not free the handle directly;
   release it with `lor_string_deinit`. */
typedef char *LorString;

#define LOR_STRING_INIT NULL

// Initializes an empty string without allocating.
void lor_string_init(LorString *string);

/* Initializes `string` with a copy of `view`.

   On failure, `string` is left empty and can be safely deinitialized. */
LorStatus lor_string_init_view(LorString *string, LorStringView view);

// NUL-terminated C-string form of `lor_string_init_view`.
LorStatus lor_string_init_cstr(LorString *string, const char *text);

// Releases owned storage and resets `string` to `LOR_STRING_INIT`.
void lor_string_deinit(LorString *string);

/* Scope-exit cleanup for `LorString` on GCC and Clang.

   Unsupported compilers leave `LOR_AUTO_STRING` empty, so explicit
   `lor_string_deinit` remains required for portable ownership paths. */
#if defined(__GNUC__) || defined(__clang__)
static inline void __attribute__((unused))
lor_string_cleanup_(LorString *string) {
    lor_string_deinit(string);
}
#define LOR_AUTO_STRING __attribute__((cleanup(lor_string_cleanup_)))
#else
#define LOR_AUTO_STRING
#endif

// Removes all contents while retaining allocated capacity.
void lor_string_clear(LorString string);

// Returns the number of content bytes, excluding the trailing NUL.
size_t lor_string_size(LorString string);

// Returns the writable content capacity, excluding the trailing NUL.
size_t lor_string_capacity(LorString string);

// Returns a borrowed view of `string`, or an empty view for `NULL`.
LorStringView lor_string_view(LorString string);

// Returns a stable empty C string when `string` is `NULL`.
const char *lor_string_cstr(LorString string);

/* Ensures room for at least `capacity` content bytes.

   The string is unchanged on failure. */
LorStatus lor_string_reserve(LorString *string, size_t capacity);

// Replaces the contents with `view`. The string is unchanged on failure.
LorStatus lor_string_assign(LorString *string, LorStringView view);

// NUL-terminated C-string form of `lor_string_assign`.
LorStatus lor_string_assign_cstr(LorString *string, const char *text);

// Appends `view`. The string is unchanged on failure.
LorStatus lor_string_append(LorString *string, LorStringView view);

// NUL-terminated C-string form of `lor_string_append`.
LorStatus lor_string_append_cstr(LorString *string, const char *text);

// Appends one byte. The string is unchanged on failure.
LorStatus lor_string_append_char(LorString *string, char value);

#ifdef __cplusplus
}
#endif
#endif
#ifdef LOR_IMPLEMENTATION

// === status: implementation ===
#ifdef LOR_ENABLE_STATUS
const char *lor_status_name(LorStatus status) {
    switch (status) {
    case LOR_STATUS_OK:
        return "ok";
    case LOR_STATUS_INVALID_ARGUMENT:
        return "invalid argument";
    case LOR_STATUS_OUT_OF_MEMORY:
        return "out of memory";
    case LOR_STATUS_OVERFLOW:
        return "overflow";
    }

    return "unknown";
}
#endif

// === memory: implementation ===
#ifdef LOR_ENABLE_MEMORY
/* The implementation needs the real function names. In leakcheck builds the
   public header can macro-wrap those names to attach call-site file/line data. */

#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#else
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#include <stdalign.h>
#define LOR_ARENA_MAX_ALIGNMENT alignof(max_align_t)
#else
#define LOR_ARENA_MAX_ALIGNMENT \
    (sizeof(void *) > sizeof(double) ? sizeof(void *) : sizeof(double))
#endif

#if defined(_MSC_VER)
#define LOR_THREAD_LOCAL __declspec(thread)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define LOR_THREAD_LOCAL _Thread_local
#elif defined(__GNUC__) || defined(__clang__)
#define LOR_THREAD_LOCAL __thread
#else
#define LOR_THREAD_LOCAL
#endif

typedef enum LorLeakKind {
    LOR_LEAK_KIND_HEAP,
    LOR_LEAK_KIND_ARENA,
    LOR_LEAK_KIND_MMAP
} LorLeakKind;

#if defined(LOR_LEAKCHECK)
typedef struct LorLeakRecord LorLeakRecord;

struct LorLeakRecord {
    LorLeakRecord *next;
    LorLeakRecord *prev;
    LorLeakKind kind;
    void *ptr;
    size_t size;
    const char *file;
    int line;
};
#endif

struct LorArenaBlock {
    // Newer blocks precede older blocks in the arena's allocation history.
    LorArenaBlock *next;
    // Bytes available from the aligned data start.
    size_t capacity;
    /* Heap: usable bytes backed by the allocation, equal to capacity.
       Virtual: bytes committed from the raw block base, including metadata. */
    size_t committed;
    // Consumed usable bytes, including inter-allocation alignment padding.
    size_t used;
    /* Heap: raw allocation size. Virtual: raw reserved address-space size.
       Both include the block metadata and data-alignment slack. */
    size_t allocation_size;
    // Unaligned start marker; lor_arena__block_data returns the usable start.
    unsigned char data[];
};

#if defined(LOR_LEAKCHECK)
static LorLeakRecord *lor_memory__leaks = NULL;
#endif
static LOR_THREAD_LOCAL LorArena lor_memory__scratch_arenas[2];
static LOR_THREAD_LOCAL int lor_memory__scratch_inited[2];

static void *lor_memory__raw_malloc(size_t size) {
    return malloc(size);
}

#if defined(LOR_LEAKCHECK)
static void *lor_memory__raw_calloc(size_t count, size_t elem_size) {
    return calloc(count, elem_size);
}

static void *lor_memory__raw_realloc(void *ptr, size_t size) {
    return realloc(ptr, size);
}
#endif

static void lor_memory__raw_free(void *ptr) {
    free(ptr);
}

static int lor_memory__add_overflows_size(size_t a, size_t b) {
    return a > SIZE_MAX - b;
}

static int lor_memory__mul_overflows_size(size_t a, size_t b) {
    return b != 0 && a > SIZE_MAX / b;
}

static int lor_memory__is_power_of_two(size_t value) {
    return value != 0 && (value & (value - 1u)) == 0;
}

static size_t lor_memory__align_up(size_t value, size_t alignment) {
    size_t mask = alignment - 1u;
    return (value + mask) & ~mask;
}

static int lor_memory__align_forward(uintptr_t value, size_t alignment,
                                     uintptr_t *out) {
    uintptr_t mask = (uintptr_t)(alignment - 1u);
    if (value > UINTPTR_MAX - mask) return 0;

    *out = (value + mask) & ~mask;
    return 1;
}

#if defined(LOR_LEAKCHECK)
static void lor_leak__insert(LorLeakRecord *record) {
    record->prev = NULL;
    record->next = lor_memory__leaks;
    if (lor_memory__leaks != NULL) lor_memory__leaks->prev = record;
    lor_memory__leaks = record;
}

static void lor_leak__remove(LorLeakRecord *record) {
    if (record->prev != NULL) {
        record->prev->next = record->next;
    } else {
        lor_memory__leaks = record->next;
    }

    if (record->next != NULL) record->next->prev = record->prev;
    lor_memory__raw_free(record);
}

static LorLeakRecord *lor_leak__find(void *ptr, LorLeakKind kind) {
    for (LorLeakRecord *record = lor_memory__leaks; record != NULL;
         record = record->next)
        if (record->ptr == ptr && record->kind == kind) return record;

    return NULL;
}

static void lor_leak__track(LorLeakKind kind, void *ptr, size_t size,
                            const char *file, int line) {
    if (ptr == NULL) return;

    LorLeakRecord *record = (LorLeakRecord *)lor_memory__raw_malloc(sizeof(*record));
    if (record == NULL) return;
    record->kind = kind;
    record->ptr = ptr;
    record->size = size;
    record->file = file;
    record->line = line;
    lor_leak__insert(record);
}

static void lor_leak__untrack(LorLeakKind kind, void *ptr) {
    LorLeakRecord *record = lor_leak__find(ptr, kind);
    if (record != NULL) lor_leak__remove(record);
}

static const char *lor_leak__kind_name(LorLeakKind kind) {
    switch (kind) {
    case LOR_LEAK_KIND_HEAP:
        return "heap";
    case LOR_LEAK_KIND_ARENA:
        return "arena";
    case LOR_LEAK_KIND_MMAP:
        return "mmap";
    }

    return "unknown";
}

static size_t lor_leak__record_size(const LorLeakRecord *record) {
    if (record == NULL) return 0;
    if (record->kind == LOR_LEAK_KIND_ARENA)
        return lor_arena_committed((const LorArena *)record->ptr);
    return record->size;
}
#else
#define lor_leak__track(kind, ptr, size, file, line) ((void)0)
#define lor_leak__untrack(kind, ptr) ((void)0)
#endif

LorLeakStats lor_leakcheck_stats(void) {
    LorLeakStats stats = {0};
#if defined(LOR_LEAKCHECK)
    for (LorLeakRecord *record = lor_memory__leaks; record != NULL;
         record = record->next) {
        switch (record->kind) {
        case LOR_LEAK_KIND_HEAP:
            stats.heap_count += 1u;
            stats.heap_bytes += record->size;
            break;
        case LOR_LEAK_KIND_ARENA:
            stats.arena_count += 1u;
            break;
        case LOR_LEAK_KIND_MMAP:
            stats.mmap_count += 1u;
            stats.mmap_bytes += record->size;
            break;
        }
    }
#endif

    return stats;
}

size_t lor_leakcheck_count(void) {
    LorLeakStats stats = lor_leakcheck_stats();
    return stats.heap_count + stats.arena_count + stats.mmap_count;
}

size_t lor_leakcheck_report(FILE *out) {
    size_t count = 0;
#if defined(LOR_LEAKCHECK)
    if (out == NULL) out = stderr;

    for (LorLeakRecord *record = lor_memory__leaks; record != NULL;
         record = record->next) {
        const char *file = record->file != NULL ? record->file : "?";
        fprintf(out, "LEAK %s: %zu bytes at %p (%s:%d)\n",
                lor_leak__kind_name(record->kind), lor_leak__record_size(record),
                record->ptr, file, record->line);
        count += 1u;
    }
#else
    (void)out;
#endif

    return count;
}

#if defined(LOR_LEAKCHECK)
void *lor_malloc_debug(size_t size, const char *file, int line) {
    if (size == 0) return NULL;

    void *ptr = lor_memory__raw_malloc(size);
    lor_leak__track(LOR_LEAK_KIND_HEAP, ptr, size, file, line);
    return ptr;
}

void *lor_calloc_debug(size_t count, size_t elem_size, const char *file, int line) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size))
        return NULL;

    void *ptr = lor_memory__raw_calloc(count, elem_size);
    lor_leak__track(LOR_LEAK_KIND_HEAP, ptr, count * elem_size, file, line);
    return ptr;
}

void lor_free_debug(void *ptr, const char *file, int line) {
    (void)file;
    (void)line;
    if (ptr == NULL) return;

    lor_leak__untrack(LOR_LEAK_KIND_HEAP, ptr);
    lor_memory__raw_free(ptr);
}

void *lor_realloc_debug(void *ptr, size_t size, const char *file, int line) {
    if (ptr == NULL) return lor_malloc_debug(size, file, line);
    if (size == 0) {
        lor_free_debug(ptr, file, line);
        return NULL;
    }

    LorLeakRecord *record = lor_leak__find(ptr, LOR_LEAK_KIND_HEAP);
    void *new_ptr = lor_memory__raw_realloc(ptr, size);
    if (new_ptr == NULL) return NULL;

    if (record != NULL) {
        record->ptr = new_ptr;
        record->size = size;
        record->file = file;
        record->line = line;
    } else {
        lor_leak__track(LOR_LEAK_KIND_HEAP, new_ptr, size, file, line);
    }

    return new_ptr;
}

char *lor_strdup_debug(const char *text, const char *file, int line) {
    if (text == NULL) return NULL;

    size_t len = strlen(text);
    if (len == SIZE_MAX) return NULL;

    char *copy = (char *)lor_malloc_debug(len + 1u, file, line);
    if (copy == NULL) return NULL;

    memcpy(copy, text, len + 1u);
    return copy;
}
#endif

size_t lor_page_size(void) {
#if defined(_WIN32)
    SYSTEM_INFO info;
    GetSystemInfo(&info);
    return (size_t)info.dwPageSize;
#else
    long page_size = sysconf(_SC_PAGESIZE);
    if (page_size <= 0) return LOR_KIB(4);
    return (size_t)page_size;
#endif
}

static size_t lor_virtual__page_align(size_t size) {
    size_t page_size = lor_page_size();
    if (page_size == 0) return size;
    if (lor_memory__add_overflows_size(size, page_size - 1u)) return 0;
    return lor_memory__align_up(size, page_size);
}

static void *lor_virtual__reserve_raw(size_t size) {
#if defined(_WIN32)
    return VirtualAlloc(NULL, size, MEM_RESERVE, PAGE_READWRITE);
#else
    void *ptr = mmap(NULL, size, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    return ptr == MAP_FAILED ? NULL : ptr;
#endif
}

static int lor_virtual__commit_raw(void *ptr, size_t size) {
#if defined(_WIN32)
    return VirtualAlloc(ptr, size, MEM_COMMIT, PAGE_READWRITE) != NULL;
#else
    return mprotect(ptr, size, PROT_READ | PROT_WRITE) == 0;
#endif
}

static void lor_virtual__release_raw(void *ptr, size_t size) {
#if defined(_WIN32)
    (void)size;
    (void)VirtualFree(ptr, 0, MEM_RELEASE);
#else
    (void)munmap(ptr, size);
#endif
}

static unsigned char *lor_arena__block_data(LorArenaBlock *block) {
    uintptr_t aligned = 0;
    if (!lor_memory__align_forward((uintptr_t)block->data, LOR_ARENA_MAX_ALIGNMENT,
                                   &aligned))
        return NULL;

    return (unsigned char *)aligned;
}

static size_t lor_arena__block_header_slack(void) {
    return offsetof(LorArenaBlock, data) + LOR_ARENA_MAX_ALIGNMENT - 1u;
}

static LorArenaBlock *lor_arena__heap_block_new(size_t capacity) {
    size_t slack = lor_arena__block_header_slack();
    if (lor_memory__add_overflows_size(capacity, slack)) return NULL;

    size_t allocation_size = capacity + slack;
    LorArenaBlock *block = (LorArenaBlock *)lor_memory__raw_malloc(allocation_size);
    if (block == NULL) return NULL;

    block->next = NULL;
    block->capacity = capacity;
    block->committed = capacity;
    block->used = 0;
    block->allocation_size = allocation_size;
    return block;
}

static LorArenaBlock *lor_arena__virtual_block_new(size_t reserve_size,
                                                   size_t commit_size,
                                                   size_t min_capacity) {
    size_t slack = lor_arena__block_header_slack();
    if (lor_memory__add_overflows_size(min_capacity, slack)) return NULL;

    size_t min_reserve = min_capacity + slack;
    if (reserve_size < min_reserve) reserve_size = min_reserve;
    reserve_size = lor_virtual__page_align(reserve_size);
    if (reserve_size == 0) return NULL;

    if (commit_size < slack) commit_size = slack;
    if (commit_size < min_reserve && min_reserve < LOR_ARENA_DEFAULT_COMMIT_SIZE)
        commit_size = min_reserve;
    commit_size = lor_virtual__page_align(commit_size);
    if (commit_size > reserve_size) commit_size = reserve_size;

    LorArenaBlock *block = (LorArenaBlock *)lor_virtual__reserve_raw(reserve_size);
    if (block == NULL) return NULL;
    if (commit_size != 0 && !lor_virtual__commit_raw(block, commit_size)) {
        lor_virtual__release_raw(block, reserve_size);
        return NULL;
    }

    block->next = NULL;
    block->capacity = 0;
    block->committed = commit_size;
    block->used = 0;
    block->allocation_size = reserve_size;

    unsigned char *base = (unsigned char *)block;
    unsigned char *data = lor_arena__block_data(block);
    if (data == NULL) {
        lor_virtual__release_raw(block, reserve_size);
        return NULL;
    }

    size_t data_offset = (size_t)(data - base);
    block->capacity = reserve_size - data_offset;
    return block;
}

static void lor_arena__block_free(LorArena *arena, LorArenaBlock *block) {
    if (block == NULL) return;

    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL)
        lor_virtual__release_raw(block, block->allocation_size);
    else
        lor_memory__raw_free(block);
}

static int lor_arena__block_ensure_committed(LorArenaBlock *block,
                                             size_t needed_used,
                                             size_t commit_size) {
    unsigned char *base = lor_arena__block_data(block);
    unsigned char *block_base = (unsigned char *)block;
    if (base == NULL || needed_used > block->capacity) return 0;

    size_t data_offset = (size_t)(base - block_base);
    if (lor_memory__add_overflows_size(data_offset, needed_used)) return 0;

    size_t needed_total = data_offset + needed_used;
    if (needed_total <= block->committed) return 1;

    size_t new_committed = needed_total;
    if (commit_size != 0) {
        if (lor_memory__add_overflows_size(new_committed, commit_size - 1u))
            return 0;
        new_committed = lor_memory__align_up(new_committed, commit_size);
    }

    if (new_committed > block->allocation_size)
        new_committed = block->allocation_size;
    if (!lor_virtual__commit_raw(block_base + block->committed,
                                 new_committed - block->committed))
        return 0;

    block->committed = new_committed;
    return 1;
}

static void *lor_arena__block_alloc(LorArena *arena, LorArenaBlock *block,
                                    size_t size, size_t alignment) {
    unsigned char *base = lor_arena__block_data(block);
    if (base == NULL || block->used > block->capacity) return NULL;

    uintptr_t current = (uintptr_t)(base + block->used);
    uintptr_t aligned = 0;
    if (!lor_memory__align_forward(current, alignment, &aligned)) return NULL;

    size_t padding = (size_t)(aligned - current);
    if (padding > block->capacity - block->used) return NULL;
    if (size > block->capacity - block->used - padding) return NULL;

    size_t new_used = block->used + padding + size;
    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL &&
        !lor_arena__block_ensure_committed(block, new_used, arena->commit_size))
        return NULL;

    block->used = new_used;
    return (void *)aligned;
}

static LorArenaBlock *lor_arena__block_new(LorArena *arena, size_t min_capacity) {
    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL)
        return lor_arena__virtual_block_new(arena->reserve_size, arena->commit_size,
                                            min_capacity);

    if (arena->block_size < min_capacity)
        return lor_arena__heap_block_new(min_capacity);
    return lor_arena__heap_block_new(arena->block_size);
}

static int lor_arena__init_internal(LorArena *arena, LorArenaConfig config,
                                    int track_leakcheck, const char *file,
                                    int line) {
#if !defined(LOR_LEAKCHECK)
    (void)file;
    (void)line;
#endif
    if (arena == NULL) return 0;

    arena->blocks = NULL;
    arena->backend = config.backend;
    arena->block_size =
        config.block_size != 0 ? config.block_size : LOR_ARENA_DEFAULT_BLOCK_SIZE;
    arena->reserve_size = config.reserve_size != 0 ? config.reserve_size
                                                   : LOR_ARENA_DEFAULT_RESERVE_SIZE;
    arena->commit_size =
        config.commit_size != 0 ? config.commit_size : LOR_ARENA_DEFAULT_COMMIT_SIZE;

    if (arena->backend != LOR_ARENA_BACKEND_HEAP &&
        arena->backend != LOR_ARENA_BACKEND_VIRTUAL) {
        *arena = (LorArena)LOR_ARENA_INIT;
        return 0;
    }

    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
        arena->reserve_size = lor_virtual__page_align(arena->reserve_size);
        arena->commit_size = lor_virtual__page_align(arena->commit_size);
        if (arena->reserve_size == 0 || arena->commit_size == 0) {
            *arena = (LorArena)LOR_ARENA_INIT;
            return 0;
        }
    }

    if (track_leakcheck) lor_leak__track(LOR_LEAK_KIND_ARENA, arena, 0, file, line);

    return 1;
}

#if defined(LOR_LEAKCHECK)
int lor_arena_init_debug(LorArena *arena, const char *file, int line) {
    return lor_arena__init_internal(arena, (LorArenaConfig){0}, 1, file, line);
}

int lor_arena_init_config_debug(LorArena *arena, LorArenaConfig config,
                                const char *file, int line) {
    return lor_arena__init_internal(arena, config, 1, file, line);
}
#endif

int lor_arena_init(LorArena *arena) {
    return lor_arena__init_internal(arena, (LorArenaConfig){0}, 1, NULL, 0);
}

int lor_arena_init_config(LorArena *arena, LorArenaConfig config) {
    return lor_arena__init_internal(arena, config, 1, NULL, 0);
}

void lor_arena_deinit(LorArena *arena) {
    if (arena == NULL) return;

    LorArenaBlock *block = arena->blocks;
    while (block != NULL) {
        LorArenaBlock *next = block->next;
        lor_arena__block_free(arena, block);
        block = next;
    }

    lor_leak__untrack(LOR_LEAK_KIND_ARENA, arena);
    *arena = (LorArena)LOR_ARENA_INIT;
}

void lor_arena_reset(LorArena *arena) {
    if (arena == NULL) return;

    for (LorArenaBlock *block = arena->blocks; block != NULL; block = block->next)
        block->used = 0;
}

LorArenaMark lor_arena_mark(const LorArena *arena) {
    if (arena == NULL) return (LorArenaMark)LOR_ARENA_MARK_INIT;

    return (LorArenaMark){
        .block = arena->blocks,
        .used = arena->blocks != NULL ? arena->blocks->used : 0,
    };
}

static int lor_arena__has_block(const LorArena *arena, const LorArenaBlock *target) {
    if (arena == NULL || target == NULL) return 0;

    for (const LorArenaBlock *block = arena->blocks; block != NULL;
         block = block->next)
        if (block == target) return 1;

    return 0;
}

void lor_arena_rewind(LorArena *arena, LorArenaMark mark) {
    if (arena == NULL) return;

    if (mark.block == NULL) {
        for (LorArenaBlock *block = arena->blocks; block != NULL;
             block = block->next)
            block->used = 0;
        return;
    }

    if (!lor_arena__has_block(arena, mark.block)) {
        assert(!"lor_arena_rewind mark does not belong to arena");
        return;
    }

    while (arena->blocks != NULL && arena->blocks != mark.block) {
        LorArenaBlock *block = arena->blocks;
        arena->blocks = block->next;
        lor_arena__block_free(arena, block);
    }

    if (mark.used > arena->blocks->used) {
        assert(!"lor_arena_rewind mark used exceeds block used");
        return;
    }

    arena->blocks->used = mark.used;
}

static void *lor_arena__alloc_aligned(LorArena *arena, size_t size, size_t alignment,
                                      const char *file, int line) {
#if !defined(LOR_LEAKCHECK)
    (void)file;
    (void)line;
#endif

    if (arena == NULL || size == 0 || !lor_memory__is_power_of_two(alignment))
        return NULL;

    if (arena->block_size == 0 && arena->reserve_size == 0)
        if (!lor_arena__init_internal(arena, (LorArenaConfig){0}, 1, file, line))
            return NULL;

    if (arena->blocks != NULL) {
        void *result = lor_arena__block_alloc(arena, arena->blocks, size, alignment);
        if (result != NULL) return result;
    }

    size_t min_capacity = size;
    if (alignment > 1u) {
        if (lor_memory__add_overflows_size(min_capacity, alignment - 1u))
            return NULL;
        min_capacity += alignment - 1u;
    }

    LorArenaBlock *block = lor_arena__block_new(arena, min_capacity);
    if (block == NULL) return NULL;

    block->next = arena->blocks;
    arena->blocks = block;
    return lor_arena__block_alloc(arena, block, size, alignment);
}

void *lor_arena_alloc(LorArena *arena, size_t size) {
    return lor_arena__alloc_aligned(arena, size, LOR_ARENA_MAX_ALIGNMENT, NULL, 0);
}

void *lor_arena_alloc_zero(LorArena *arena, size_t size) {
    void *ptr =
        lor_arena__alloc_aligned(arena, size, LOR_ARENA_MAX_ALIGNMENT, NULL, 0);

    if (ptr != NULL) memset(ptr, 0, size);
    return ptr;
}

#if defined(LOR_LEAKCHECK)
void *lor_arena_alloc_debug(LorArena *arena, size_t size, const char *file,
                            int line) {
    return lor_arena__alloc_aligned(arena, size, LOR_ARENA_MAX_ALIGNMENT, file,
                                    line);
}

void *lor_arena_alloc_zero_debug(LorArena *arena, size_t size, const char *file,
                                 int line) {
    void *ptr =
        lor_arena__alloc_aligned(arena, size, LOR_ARENA_MAX_ALIGNMENT, file, line);

    if (ptr != NULL) memset(ptr, 0, size);
    return ptr;
}
#endif

void *lor_arena_alloc_array(LorArena *arena, size_t count, size_t elem_size) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size))
        return NULL;

    return lor_arena_alloc(arena, count * elem_size);
}

void *lor_arena_alloc_array_zero(LorArena *arena, size_t count, size_t elem_size) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size))
        return NULL;

    return lor_arena_alloc_zero(arena, count * elem_size);
}

#if defined(LOR_LEAKCHECK)
void *lor_arena_alloc_array_debug(LorArena *arena, size_t count, size_t elem_size,
                                  const char *file, int line) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size))
        return NULL;

    return lor_arena_alloc_debug(arena, count * elem_size, file, line);
}

void *lor_arena_alloc_array_zero_debug(LorArena *arena, size_t count,
                                       size_t elem_size, const char *file,
                                       int line) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size))
        return NULL;

    return lor_arena_alloc_zero_debug(arena, count * elem_size, file, line);
}
#endif

static char *lor_arena__strdup_at(LorArena *arena, const char *text,
                                  const char *file, int line) {
    if (text == NULL) return NULL;

    size_t len = strlen(text);
    if (len == SIZE_MAX) return NULL;

    char *copy = (char *)lor_arena__alloc_aligned(
        arena, len + 1u, LOR_ARENA_MAX_ALIGNMENT, file, line);
    if (copy == NULL) return NULL;

    memcpy(copy, text, len + 1u);
    return copy;
}

char *lor_arena_strdup(LorArena *arena, const char *text) {
    return lor_arena__strdup_at(arena, text, NULL, 0);
}

#if defined(LOR_LEAKCHECK)
char *lor_arena_strdup_debug(LorArena *arena, const char *text, const char *file,
                             int line) {
    return lor_arena__strdup_at(arena, text, file, line);
}
#endif

size_t lor_arena_used(const LorArena *arena) {
    if (arena == NULL) return 0;

    size_t total = 0;
    for (const LorArenaBlock *block = arena->blocks; block != NULL;
         block = block->next)
        total += block->used;
    return total;
}

size_t lor_arena_capacity(const LorArena *arena) {
    if (arena == NULL) return 0;

    size_t total = 0;
    for (const LorArenaBlock *block = arena->blocks; block != NULL;
         block = block->next)
        total += block->capacity;
    return total;
}

size_t lor_arena_committed(const LorArena *arena) {
    if (arena == NULL) return 0;

    size_t total = 0;
    for (const LorArenaBlock *block = arena->blocks; block != NULL;
         block = block->next) {
        if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
            unsigned char *base = (unsigned char *)block;
            unsigned char *data = lor_arena__block_data((LorArenaBlock *)block);
            size_t data_offset = data != NULL ? (size_t)(data - base) : 0;
            if (block->committed > data_offset)
                total += block->committed - data_offset;
        } else
            total += block->committed;
    }
    return total;
}

LorScratch lor_scratch_begin(LorArena **conflicts, size_t conflict_count) {
    for (size_t i = 0; i < 2u; ++i) {
        int conflict = 0;
        for (size_t j = 0; j < conflict_count; ++j) {
            if (conflicts != NULL &&
                conflicts[j] == &lor_memory__scratch_arenas[i]) {
                conflict = 1;
                break;
            }
        }

        if (conflict) continue;

        if (!lor_memory__scratch_inited[i]) {
            LorArenaConfig config = {
                .backend = LOR_ARENA_BACKEND_HEAP,
                .block_size = LOR_ARENA_DEFAULT_BLOCK_SIZE,
            };
            if (!lor_arena__init_internal(&lor_memory__scratch_arenas[i], config, 0,
                                          NULL, 0))
                return (LorScratch)LOR_SCRATCH_INIT;
            lor_memory__scratch_inited[i] = 1;
        }

        return (LorScratch){
            .arena = &lor_memory__scratch_arenas[i],
            .mark = lor_arena_mark(&lor_memory__scratch_arenas[i]),
        };
    }

    return (LorScratch)LOR_SCRATCH_INIT;
}

void lor_scratch_end(LorScratch scratch) {
    if (scratch.arena == NULL) return;
    lor_arena_rewind(scratch.arena, scratch.mark);
}

void lor_scratch_cleanup(void) {
    for (size_t i = 0; i < 2u; ++i) {
        if (lor_memory__scratch_inited[i]) {
            lor_arena_deinit(&lor_memory__scratch_arenas[i]);
            lor_memory__scratch_inited[i] = 0;
        }
    }
}

#if defined(_WIN32)
static DWORD lor_mmap__windows_protect(LorMmapMode mode) {
    switch (mode) {
    case LOR_MMAP_SHARED:
        return PAGE_READWRITE;
    case LOR_MMAP_COPY:
        return PAGE_WRITECOPY;
    case LOR_MMAP_READ:
        return PAGE_READONLY;
    }
    return PAGE_READONLY;
}

static DWORD lor_mmap__windows_access(LorMmapMode mode) {
    switch (mode) {
    case LOR_MMAP_SHARED:
        return FILE_MAP_WRITE;
    case LOR_MMAP_COPY:
        return FILE_MAP_COPY;
    case LOR_MMAP_READ:
        return FILE_MAP_READ;
    }
    return FILE_MAP_READ;
}
#endif

static int lor_mmap__mode_valid(LorMmapMode mode) {
    return mode == LOR_MMAP_READ || mode == LOR_MMAP_COPY ||
           mode == LOR_MMAP_SHARED;
}

static LorMmap lor_mmap__file_at(const char *path, LorMmapMode mode,
                                 const char *file, int line) {
    LorMmap map = {0};
#if !defined(LOR_LEAKCHECK)
    (void)file;
    (void)line;
#endif
    if (path == NULL || !lor_mmap__mode_valid(mode)) return map;

#if defined(_WIN32)
    {
        DWORD access =
            mode == LOR_MMAP_SHARED ? GENERIC_READ | GENERIC_WRITE : GENERIC_READ;
        DWORD create = OPEN_EXISTING;
        LARGE_INTEGER file_size;
        HANDLE file_handle =
            CreateFileA(path, access, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL,
                        create, FILE_ATTRIBUTE_NORMAL, NULL);

        if (file_handle == INVALID_HANDLE_VALUE) return map;
        if (!GetFileSizeEx(file_handle, &file_size) || file_size.QuadPart <= 0) {
            CloseHandle(file_handle);
            return map;
        }
        if ((uint64_t)file_size.QuadPart > SIZE_MAX) {
            CloseHandle(file_handle);
            return map;
        }

        HANDLE mapping = CreateFileMappingA(
            file_handle, NULL, lor_mmap__windows_protect(mode), 0, 0, NULL);
        CloseHandle(file_handle);
        if (mapping == NULL) return map;

        map.data = MapViewOfFile(mapping, lor_mmap__windows_access(mode), 0, 0, 0);
        CloseHandle(mapping);
        if (map.data == NULL) return (LorMmap){0};

        map.size = (size_t)file_size.QuadPart;
    }
#else
    {
        int flags = mode == LOR_MMAP_SHARED ? O_RDWR : O_RDONLY;
        int prot = PROT_READ;
        int mmap_flags = mode == LOR_MMAP_SHARED ? MAP_SHARED : MAP_PRIVATE;
        struct stat st;
        int fd = open(path, flags);

        if (fd < 0) return map;
        if (fstat(fd, &st) != 0 || st.st_size <= 0) {
            close(fd);
            return map;
        }
        if ((uint64_t)st.st_size > SIZE_MAX) {
            close(fd);
            return map;
        }

        if (mode != LOR_MMAP_READ) prot |= PROT_WRITE;

        map.size = (size_t)st.st_size;
        map.data = mmap(NULL, map.size, prot, mmap_flags, fd, 0);
        close(fd);
        if (map.data == MAP_FAILED) return (LorMmap){0};
    }
#endif

    lor_leak__track(LOR_LEAK_KIND_MMAP, map.data, map.size, file, line);
    return map;
}

#if defined(LOR_LEAKCHECK)
LorMmap lor_mmap_file_debug(const char *path, LorMmapMode mode, const char *file,
                            int line) {
    return lor_mmap__file_at(path, mode, file, line);
}
#endif

LorMmap lor_mmap_file(const char *path, LorMmapMode mode) {
    return lor_mmap__file_at(path, mode, NULL, 0);
}

void lor_mmap_unmap(LorMmap *map) {
    if (map == NULL || map->data == NULL) return;

    lor_leak__untrack(LOR_LEAK_KIND_MMAP, map->data);

#if defined(_WIN32)
    (void)UnmapViewOfFile(map->data);
#else
    (void)munmap(map->data, map->size);
#endif

    map->data = NULL;
    map->size = 0;
}
#endif

// === string: implementation ===
#ifdef LOR_ENABLE_STRING
#if defined(LOR_LEAKCHECK)
#endif

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static int lor_sv__ascii_space(unsigned char value) {
    return value == ' ' || value == '\t' || value == '\n' || value == '\r' ||
           value == '\f' || value == '\v';
}

static const char *lor_sv__offset(LorStringView view, size_t offset) {
    return view.data != NULL ? view.data + offset : NULL;
}

LorStringView lor_sv_from_parts(const char *data, size_t size) {
    if (data == NULL && size != 0) return (LorStringView)LOR_STRING_VIEW_INIT;
    return (LorStringView){.data = data, .size = size};
}

LorStringView lor_sv_from_cstr(const char *text) {
    if (text == NULL) return (LorStringView)LOR_STRING_VIEW_INIT;
    return lor_sv_from_parts(text, strlen(text));
}

int lor_sv_is_valid(LorStringView view) {
    return view.data != NULL || view.size == 0;
}

int lor_sv_is_empty(LorStringView view) {
    return view.size == 0;
}

int lor_sv_equal(LorStringView a, LorStringView b) {
    if (!lor_sv_is_valid(a) || !lor_sv_is_valid(b) || a.size != b.size) return 0;
    if (a.size == 0) return 1;
    return memcmp(a.data, b.data, a.size) == 0;
}

int lor_sv_starts_with(LorStringView view, LorStringView prefix) {
    if (!lor_sv_is_valid(view) || !lor_sv_is_valid(prefix) ||
        prefix.size > view.size)
        return 0;

    return lor_sv_equal(lor_sv_take_left(view, prefix.size), prefix);
}

int lor_sv_ends_with(LorStringView view, LorStringView suffix) {
    if (!lor_sv_is_valid(view) || !lor_sv_is_valid(suffix) ||
        suffix.size > view.size)
        return 0;

    return lor_sv_equal(lor_sv_take_right(view, suffix.size), suffix);
}

LorStringView lor_sv_trim_left(LorStringView view) {
    if (!lor_sv_is_valid(view)) return (LorStringView)LOR_STRING_VIEW_INIT;

    size_t offset = 0;
    while (offset < view.size &&
           lor_sv__ascii_space((unsigned char)view.data[offset]))
        offset += 1u;

    return lor_sv_slice(view, offset, view.size - offset);
}

LorStringView lor_sv_trim_right(LorStringView view) {
    if (!lor_sv_is_valid(view)) return (LorStringView)LOR_STRING_VIEW_INIT;

    size_t size = view.size;
    while (size > 0 && lor_sv__ascii_space((unsigned char)view.data[size - 1u]))
        size -= 1u;

    return lor_sv_slice(view, 0, size);
}

LorStringView lor_sv_trim(LorStringView view) {
    return lor_sv_trim_right(lor_sv_trim_left(view));
}

LorStringView lor_sv_slice(LorStringView view, size_t offset, size_t size) {
    if (!lor_sv_is_valid(view)) return (LorStringView)LOR_STRING_VIEW_INIT;
    if (offset > view.size) offset = view.size;
    if (size > view.size - offset) size = view.size - offset;
    return lor_sv_from_parts(lor_sv__offset(view, offset), size);
}

LorStringView lor_sv_take_left(LorStringView view, size_t size) {
    return lor_sv_slice(view, 0, size);
}

LorStringView lor_sv_take_right(LorStringView view, size_t size) {
    if (!lor_sv_is_valid(view)) return (LorStringView)LOR_STRING_VIEW_INIT;
    if (size > view.size) size = view.size;
    return lor_sv_slice(view, view.size - size, size);
}

LorStringView lor_sv_chop_left(LorStringView *view, size_t size) {
    if (view == NULL || !lor_sv_is_valid(*view))
        return (LorStringView)LOR_STRING_VIEW_INIT;

    LorStringView result = lor_sv_take_left(*view, size);
    *view = lor_sv_slice(*view, result.size, view->size - result.size);
    return result;
}

LorStringView lor_sv_chop_right(LorStringView *view, size_t size) {
    if (view == NULL || !lor_sv_is_valid(*view))
        return (LorStringView)LOR_STRING_VIEW_INIT;

    LorStringView result = lor_sv_take_right(*view, size);
    view->size -= result.size;
    return result;
}

int lor_sv_find(LorStringView view, LorStringView needle, size_t *index) {
    if (!lor_sv_is_valid(view) || !lor_sv_is_valid(needle) ||
        needle.size > view.size)
        return 0;

    if (needle.size == 0) {
        if (index != NULL) *index = 0;
        return 1;
    }

    size_t limit = view.size - needle.size;
    for (size_t i = 0; i <= limit; ++i) {
        if (view.data[i] == needle.data[0] &&
            memcmp(view.data + i, needle.data, needle.size) == 0) {
            if (index != NULL) *index = i;
            return 1;
        }
    }

    return 0;
}

int lor_sv_find_char(LorStringView view, char needle, size_t *index) {
    if (!lor_sv_is_valid(view)) return 0;

    const char *found = view.size != 0 ? memchr(view.data, needle, view.size) : NULL;
    if (found == NULL) return 0;
    if (index != NULL) *index = (size_t)(found - view.data);
    return 1;
}

int lor_sv_split_once(LorStringView view, LorStringView delimiter,
                      LorStringView *before, LorStringView *after) {
    size_t index = 0;
    int found = delimiter.size != 0 && lor_sv_find(view, delimiter, &index);

    if (before != NULL) *before = found ? lor_sv_take_left(view, index) : view;
    if (after != NULL) {
        *after = found
                     ? lor_sv_slice(view, index + delimiter.size,
                                    view.size - index - delimiter.size)
                     : (LorStringView)LOR_STRING_VIEW_INIT;
    }

    return found;
}

int lor_sv_split_once_char(LorStringView view, char delimiter,
                           LorStringView *before, LorStringView *after) {
    return lor_sv_split_once(view, lor_sv_from_parts(&delimiter, 1), before,
                             after);
}

int lor_sv_chop(LorStringView *view, LorStringView delimiter,
                LorStringView *part) {
    if (view == NULL || !lor_sv_is_valid(*view) ||
        !lor_sv_is_valid(delimiter) || delimiter.size == 0) {
        if (part != NULL) *part = (LorStringView)LOR_STRING_VIEW_INIT;
        return 0;
    }

    LorStringView before;
    LorStringView after;
    int found = lor_sv_split_once(*view, delimiter, &before, &after);
    if (part != NULL) *part = before;

    if (found) {
        *view = after;
    } else {
        *view = lor_sv_slice(*view, view->size, 0);
    }

    return found;
}

int lor_sv_chop_char(LorStringView *view, char delimiter, LorStringView *part) {
    return lor_sv_chop(view, lor_sv_from_parts(&delimiter, 1), part);
}

int lor_sv_fprint(FILE *out, LorStringView view) {
    if (out == NULL || !lor_sv_is_valid(view)) return 0;
    if (view.size == 0) return 1;
    return fwrite(view.data, 1, view.size, out) == view.size;
}

int lor_sv_print(LorStringView view) {
    return lor_sv_fprint(stdout, view);
}

typedef struct LorStringHeader {
    size_t size;
    size_t capacity;
    char data[];
} LorStringHeader;

static LorStringHeader *lor_string__header(LorString string) {
    return (LorStringHeader *)((unsigned char *)string -
                               offsetof(LorStringHeader, data));
}

static const LorStringHeader *lor_string__header_const(LorString string) {
    return (const LorStringHeader *)((const unsigned char *)string -
                                     offsetof(LorStringHeader, data));
}

static void *lor_string__realloc(void *ptr, size_t size) {
#if defined(LOR_LEAKCHECK)
    return lor_realloc_debug(ptr, size, __FILE__, __LINE__);
#else
    return realloc(ptr, size);
#endif
}

static void lor_string__free(void *ptr) {
#if defined(LOR_LEAKCHECK)
    lor_free_debug(ptr, __FILE__, __LINE__);
#else
    free(ptr);
#endif
}

/* Returns one for a valid alias, zero for no alias, and negative one when a
   view begins inside the string but extends beyond its initialized bytes. */
static int lor_string__view_offset(LorString string, LorStringView view,
                                   size_t *offset) {
    if (string == NULL || view.data == NULL) return 0;

    size_t string_size = lor_string__header_const(string)->size;
    uintptr_t base = (uintptr_t)(const void *)string;
    uintptr_t start = (uintptr_t)(const void *)view.data;
    if (string_size > UINTPTR_MAX - base) return 0;

    uintptr_t end = base + string_size;
    if (start < base || start > end) return 0;

    size_t result = (size_t)(start - base);
    if (view.size > string_size - result) return -1;
    if (offset != NULL) *offset = result;
    return 1;
}

static LorStatus lor_string__growth_capacity(size_t current, size_t required,
                                             size_t *capacity) {
    if (required == SIZE_MAX) return LOR_STATUS_OVERFLOW;

    size_t result = current < 16u ? 16u : current;
    while (result < required) {
        if (result > SIZE_MAX / 2u) {
            result = required;
            break;
        }
        result *= 2u;
    }

    if (result == SIZE_MAX) return LOR_STATUS_OVERFLOW;
    *capacity = result;
    return LOR_STATUS_OK;
}

void lor_string_init(LorString *string) {
    if (string != NULL) *string = LOR_STRING_INIT;
}

LorStatus lor_string_init_view(LorString *string, LorStringView view) {
    if (string == NULL) return LOR_STATUS_INVALID_ARGUMENT;
    *string = LOR_STRING_INIT;
    return lor_string_assign(string, view);
}

LorStatus lor_string_init_cstr(LorString *string, const char *text) {
    if (string == NULL) return LOR_STATUS_INVALID_ARGUMENT;
    *string = LOR_STRING_INIT;
    if (text == NULL) return LOR_STATUS_INVALID_ARGUMENT;
    return lor_string_assign(string, lor_sv_from_cstr(text));
}

void lor_string_deinit(LorString *string) {
    if (string == NULL) return;
    if (*string != NULL) lor_string__free(lor_string__header(*string));
    *string = LOR_STRING_INIT;
}

void lor_string_clear(LorString string) {
    if (string == NULL) return;
    lor_string__header(string)->size = 0;
    string[0] = '\0';
}

size_t lor_string_size(LorString string) {
    return string != NULL ? lor_string__header_const(string)->size : 0;
}

size_t lor_string_capacity(LorString string) {
    return string != NULL ? lor_string__header_const(string)->capacity : 0;
}

LorStringView lor_string_view(LorString string) {
    return lor_sv_from_parts(string, lor_string_size(string));
}

const char *lor_string_cstr(LorString string) {
    return string != NULL ? string : "";
}

LorStatus lor_string_reserve(LorString *string, size_t capacity) {
    if (string == NULL) return LOR_STATUS_INVALID_ARGUMENT;

    size_t current_capacity = lor_string_capacity(*string);
    if (capacity <= current_capacity) return LOR_STATUS_OK;

    size_t new_capacity = 0;
    LorStatus status =
        lor_string__growth_capacity(current_capacity, capacity, &new_capacity);
    if (status != LOR_STATUS_OK) return status;

    size_t header_size = offsetof(LorStringHeader, data);
    if (new_capacity > SIZE_MAX - header_size - 1u)
        return LOR_STATUS_OVERFLOW;

    size_t size = lor_string_size(*string);
    LorStringHeader *header =
        *string != NULL ? lor_string__header(*string) : NULL;
    LorStringHeader *new_header = (LorStringHeader *)lor_string__realloc(
        header, header_size + new_capacity + 1u);
    if (new_header == NULL) return LOR_STATUS_OUT_OF_MEMORY;

    new_header->size = size;
    new_header->capacity = new_capacity;
    new_header->data[size] = '\0';
    *string = new_header->data;
    return LOR_STATUS_OK;
}

LorStatus lor_string_assign(LorString *string, LorStringView view) {
    if (string == NULL || !lor_sv_is_valid(view))
        return LOR_STATUS_INVALID_ARGUMENT;

    size_t offset = 0;
    int alias = lor_string__view_offset(*string, view, &offset);
    if (alias < 0) return LOR_STATUS_INVALID_ARGUMENT;

    LorStatus status = lor_string_reserve(string, view.size);
    if (status != LOR_STATUS_OK) return status;
    if (alias > 0) view.data = *string + offset;

    if (view.size != 0) memmove(*string, view.data, view.size);
    if (*string != NULL) {
        lor_string__header(*string)->size = view.size;
        (*string)[view.size] = '\0';
    }
    return LOR_STATUS_OK;
}

LorStatus lor_string_assign_cstr(LorString *string, const char *text) {
    if (text == NULL) return LOR_STATUS_INVALID_ARGUMENT;
    return lor_string_assign(string, lor_sv_from_cstr(text));
}

LorStatus lor_string_append(LorString *string, LorStringView view) {
    if (string == NULL || !lor_sv_is_valid(view))
        return LOR_STATUS_INVALID_ARGUMENT;
    if (view.size == 0) return LOR_STATUS_OK;

    size_t old_size = lor_string_size(*string);
    if (view.size > SIZE_MAX - old_size) return LOR_STATUS_OVERFLOW;

    size_t offset = 0;
    int alias = lor_string__view_offset(*string, view, &offset);
    if (alias < 0) return LOR_STATUS_INVALID_ARGUMENT;

    size_t new_size = old_size + view.size;
    LorStatus status = lor_string_reserve(string, new_size);
    if (status != LOR_STATUS_OK) return status;
    if (alias > 0) view.data = *string + offset;

    memmove(*string + old_size, view.data, view.size);
    lor_string__header(*string)->size = new_size;
    (*string)[new_size] = '\0';
    return LOR_STATUS_OK;
}

LorStatus lor_string_append_cstr(LorString *string, const char *text) {
    if (text == NULL) return LOR_STATUS_INVALID_ARGUMENT;
    return lor_string_append(string, lor_sv_from_cstr(text));
}

LorStatus lor_string_append_char(LorString *string, char value) {
    return lor_string_append(string, lor_sv_from_parts(&value, 1));
}
#endif

#endif
/* Optional short-name aliases
   These are preprocessor aliases only. They do not change compiled
   symbol names. */
#ifdef LOR_STRIP_PREFIX
#ifdef LOR_ENABLE_STATUS
#define Status LorStatus
#define STATUS_OK LOR_STATUS_OK
#define STATUS_INVALID_ARGUMENT LOR_STATUS_INVALID_ARGUMENT
#define STATUS_OUT_OF_MEMORY LOR_STATUS_OUT_OF_MEMORY
#define STATUS_OVERFLOW LOR_STATUS_OVERFLOW
#define status_name lor_status_name
#endif
#ifdef LOR_ENABLE_MEMORY
#define ArenaBackend LorArenaBackend
#define ArenaConfig LorArenaConfig
#define Arena LorArena
#define ArenaMark LorArenaMark
#define ArenaBlock LorArenaBlock
#define Scratch LorScratch
#define MmapMode LorMmapMode
#define Mmap LorMmap
#define LeakStats LorLeakStats
#define KIB LOR_KIB
#define MIB LOR_MIB
#define GIB LOR_GIB
#define ARENA_BACKEND_HEAP LOR_ARENA_BACKEND_HEAP
#define ARENA_BACKEND_VIRTUAL LOR_ARENA_BACKEND_VIRTUAL
#define ARENA_DEFAULT_BLOCK_SIZE LOR_ARENA_DEFAULT_BLOCK_SIZE
#define ARENA_DEFAULT_RESERVE_SIZE LOR_ARENA_DEFAULT_RESERVE_SIZE
#define ARENA_DEFAULT_COMMIT_SIZE LOR_ARENA_DEFAULT_COMMIT_SIZE
#define ARENA_INIT LOR_ARENA_INIT
#define ARENA_MARK_INIT LOR_ARENA_MARK_INIT
#define SCRATCH_INIT LOR_SCRATCH_INIT
#define MMAP_READ LOR_MMAP_READ
#define MMAP_COPY LOR_MMAP_COPY
#define MMAP_SHARED LOR_MMAP_SHARED
#define CLEANUP_SUPPORTED LOR_CLEANUP_SUPPORTED
#define CLEANUP LOR_CLEANUP
#define AUTO_FREE LOR_AUTO_FREE
#define AUTO_ARENA LOR_AUTO_ARENA
#define AUTO_SCRATCH LOR_AUTO_SCRATCH
#define AUTO_MMAP LOR_AUTO_MMAP
#define AUTO_FILE LOR_AUTO_FILE
#define arena_init lor_arena_init
#define arena_init_config lor_arena_init_config
#define arena_deinit lor_arena_deinit
#define arena_reset lor_arena_reset
#define arena_mark lor_arena_mark
#define arena_rewind lor_arena_rewind
#define arena_alloc lor_arena_alloc
#define arena_alloc_zero lor_arena_alloc_zero
#define arena_alloc_array lor_arena_alloc_array
#define arena_alloc_array_zero lor_arena_alloc_array_zero
#define arena_strdup lor_arena_strdup
#define arena_used lor_arena_used
#define arena_capacity lor_arena_capacity
#define arena_committed lor_arena_committed
#define scratch_begin lor_scratch_begin
#define scratch_end lor_scratch_end
#define scratch_cleanup lor_scratch_cleanup
#define page_size lor_page_size
#define mmap_file lor_mmap_file
#define mmap_unmap lor_mmap_unmap
#define leakcheck_stats lor_leakcheck_stats
#define leakcheck_count lor_leakcheck_count
#define leakcheck_report lor_leakcheck_report
#endif
#ifdef LOR_ENABLE_STRING
#define StringView LorStringView
#define String LorString
#define STRING_VIEW_INIT LOR_STRING_VIEW_INIT
#define SV_LITERAL LOR_SV_LITERAL
#define STRING_INIT LOR_STRING_INIT
#define AUTO_STRING LOR_AUTO_STRING
#define sv_from_parts lor_sv_from_parts
#define sv_from_cstr lor_sv_from_cstr
#define sv_is_valid lor_sv_is_valid
#define sv_is_empty lor_sv_is_empty
#define sv_equal lor_sv_equal
#define sv_starts_with lor_sv_starts_with
#define sv_ends_with lor_sv_ends_with
#define sv_trim_left lor_sv_trim_left
#define sv_trim_right lor_sv_trim_right
#define sv_trim lor_sv_trim
#define sv_slice lor_sv_slice
#define sv_take_left lor_sv_take_left
#define sv_take_right lor_sv_take_right
#define sv_chop_left lor_sv_chop_left
#define sv_chop_right lor_sv_chop_right
#define sv_find lor_sv_find
#define sv_find_char lor_sv_find_char
#define sv_split_once lor_sv_split_once
#define sv_split_once_char lor_sv_split_once_char
#define sv_chop lor_sv_chop
#define sv_chop_char lor_sv_chop_char
#define sv_fprint lor_sv_fprint
#define sv_print lor_sv_print
#define string_init lor_string_init
#define string_init_view lor_string_init_view
#define string_init_cstr lor_string_init_cstr
#define string_deinit lor_string_deinit
#define string_clear lor_string_clear
#define string_size lor_string_size
#define string_capacity lor_string_capacity
#define string_view lor_string_view
#define string_cstr lor_string_cstr
#define string_reserve lor_string_reserve
#define string_assign lor_string_assign
#define string_assign_cstr lor_string_assign_cstr
#define string_append lor_string_append
#define string_append_cstr lor_string_append_cstr
#define string_append_char lor_string_append_char
#endif
#endif

#undef LOR_SINGLE_HEADER_BUILD
// === memory: post-implementation macros ===
#ifdef LOR_ENABLE_MEMORY
/* Leakcheck location capture.

   These macros are deliberately kept at the end of the header. In normal
   multi-file builds they affect user code after all declarations are visible.
   In the generated single-header they are emitted after the implementation, so
   they do not rewrite liblor's own function definitions.

   src/memory.c defines LOR_MEMORY_NO_LOCATION_MACROS and
   LOR_MEMORY_NO_STDLIB_MACROS before including this header because the
   implementation needs to define and call the real functions. */
#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_LOCATION_MACROS) && \
    !defined(LOR_SINGLE_HEADER_BUILD)
#undef lor_arena_init
#define lor_arena_init(arena) lor_arena_init_debug((arena), __FILE__, __LINE__)
#undef lor_arena_init_config
#define lor_arena_init_config(arena, ...) \
    lor_arena_init_config_debug((arena), __VA_ARGS__, __FILE__, __LINE__)
#undef lor_arena_alloc
#define lor_arena_alloc(arena, size) \
    lor_arena_alloc_debug((arena), (size), __FILE__, __LINE__)
#undef lor_arena_alloc_zero
#define lor_arena_alloc_zero(arena, size) \
    lor_arena_alloc_zero_debug((arena), (size), __FILE__, __LINE__)
#undef lor_arena_alloc_array
#define lor_arena_alloc_array(arena, count, elem_size) \
    lor_arena_alloc_array_debug((arena), (count), (elem_size), __FILE__, __LINE__)
#undef lor_arena_alloc_array_zero
#define lor_arena_alloc_array_zero(arena, count, elem_size)                   \
    lor_arena_alloc_array_zero_debug((arena), (count), (elem_size), __FILE__, \
                                     __LINE__)
#undef lor_arena_strdup
#define lor_arena_strdup(arena, text) \
    lor_arena_strdup_debug((arena), (text), __FILE__, __LINE__)
#undef lor_mmap_file
#define lor_mmap_file(path, mode) \
    lor_mmap_file_debug((path), (mode), __FILE__, __LINE__)
#endif

#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_STDLIB_MACROS) && \
    !defined(LOR_SINGLE_HEADER_BUILD)
#define malloc(size) lor_malloc_debug((size), __FILE__, __LINE__)
#define calloc(count, elem_size) \
    lor_calloc_debug((count), (elem_size), __FILE__, __LINE__)
#define realloc(ptr, size) lor_realloc_debug((ptr), (size), __FILE__, __LINE__)
#define free(ptr) lor_free_debug((ptr), __FILE__, __LINE__)
#define strdup(text) lor_strdup_debug((text), __FILE__, __LINE__)
#endif
#endif

#endif // LOR_SINGLE_HEADER_H
