// SPDX-License-Identifier: MIT
/*
   liblor in a single-header.
   Generated by tools/gen_single_header.py; do not edit by hand.
*/

#ifndef LOR_SINGLE_HEADER_H
#define LOR_SINGLE_HEADER_H
#define LOR_SINGLE_HEADER_BUILD

/* Module selection
   If no LOR_ENABLE_* macro is defined, every stable module is enabled.
   Define one or more LOR_ENABLE_* macros before including this header
   to include only those modules. */
#if !defined(LOR_ENABLE_MEMORY)
#define LOR_ENABLE_ALL
#endif

#ifdef LOR_ENABLE_ALL
#define LOR_ENABLE_MEMORY
#endif

/* Optional compiled function prefix
   Example: #define LOR_CUSTOM_PREFIX my_
   turns lor_arena_init into my_arena_init in this translation unit.
   This affects declarations and definitions, so all translation units
   using the generated header must use the same custom prefix. */
#ifdef LOR_CUSTOM_PREFIX
#define LOR__JOIN2(a, b) a##b
#define LOR__JOIN(a, b) LOR__JOIN2(a, b)
#ifdef LOR_ENABLE_MEMORY
#define lor_arena_init LOR__JOIN(LOR_CUSTOM_PREFIX, arena_init)
#define lor_arena_init_ex LOR__JOIN(LOR_CUSTOM_PREFIX, arena_init_ex)
#define lor_arena_deinit LOR__JOIN(LOR_CUSTOM_PREFIX, arena_deinit)
#define lor_arena_reset LOR__JOIN(LOR_CUSTOM_PREFIX, arena_reset)
#define lor_arena_mark LOR__JOIN(LOR_CUSTOM_PREFIX, arena_mark)
#define lor_arena_rewind LOR__JOIN(LOR_CUSTOM_PREFIX, arena_rewind)
#define lor_arena_alloc LOR__JOIN(LOR_CUSTOM_PREFIX, arena_alloc)
#define lor_arena_alloc_zero LOR__JOIN(LOR_CUSTOM_PREFIX, arena_alloc_zero)
#define lor_arena_alloc_array LOR__JOIN(LOR_CUSTOM_PREFIX, arena_alloc_array)
#define lor_arena_alloc_array_zero LOR__JOIN(LOR_CUSTOM_PREFIX, arena_alloc_array_zero)
#define lor_arena_strdup LOR__JOIN(LOR_CUSTOM_PREFIX, arena_strdup)
#define lor_arena_used LOR__JOIN(LOR_CUSTOM_PREFIX, arena_used)
#define lor_arena_capacity LOR__JOIN(LOR_CUSTOM_PREFIX, arena_capacity)
#define lor_arena_committed LOR__JOIN(LOR_CUSTOM_PREFIX, arena_committed)
#define lor_scratch_begin LOR__JOIN(LOR_CUSTOM_PREFIX, scratch_begin)
#define lor_scratch_end LOR__JOIN(LOR_CUSTOM_PREFIX, scratch_end)
#define lor_scratch_cleanup_current_thread LOR__JOIN(LOR_CUSTOM_PREFIX, scratch_cleanup_current_thread)
#define lor_page_size LOR__JOIN(LOR_CUSTOM_PREFIX, page_size)
#define lor_mmap_file LOR__JOIN(LOR_CUSTOM_PREFIX, mmap_file)
#define lor_mmap_unmap LOR__JOIN(LOR_CUSTOM_PREFIX, mmap_unmap)
#define lor_leakcheck_stats LOR__JOIN(LOR_CUSTOM_PREFIX, leakcheck_stats)
#define lor_leakcheck_count LOR__JOIN(LOR_CUSTOM_PREFIX, leakcheck_count)
#define lor_leakcheck_report LOR__JOIN(LOR_CUSTOM_PREFIX, leakcheck_report)
#endif
#endif

/* === memory: declarations === */
#ifdef LOR_ENABLE_MEMORY
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define LOR_KIB(n) ((size_t)(n) << 10)
#define LOR_MIB(n) ((size_t)(n) << 20)
#define LOR_GIB(n) ((size_t)(n) << 30)

#define LOR_ARENA_DEFAULT_BLOCK_SIZE LOR_KIB(64)
#define LOR_ARENA_DEFAULT_RESERVE_SIZE LOR_MIB(64)
#define LOR_ARENA_DEFAULT_COMMIT_SIZE LOR_KIB(64)

typedef enum LorArenaBackend {
    LOR_ARENA_BACKEND_HEAP = 0,
    LOR_ARENA_BACKEND_VIRTUAL = 1
} LorArenaBackend;

typedef struct LorArenaBlock LorArenaBlock;
typedef struct LorArenaScope LorArenaScope;

typedef struct LorArenaConfig {
    LorArenaBackend backend;
    size_t block_size;
    size_t reserve_size;
    size_t commit_size;
} LorArenaConfig;

typedef struct LorArena {
    LorArenaBlock *blocks;
    LorArenaScope *scopes;
    LorArenaBackend backend;
    size_t block_size;
    size_t reserve_size;  // capacity
    size_t commit_size;   // allocation size
} LorArena;

typedef struct LorScratch {
    LorArena *arena;
    LorArenaBlock *block;
    size_t used;
} LorScratch;

#define LOR_ARENA_INIT {NULL, NULL, LOR_ARENA_BACKEND_HEAP, 0u, 0u, 0u}

void lor_arena_init(LorArena *arena, size_t block_size);
int lor_arena_init_ex(LorArena *arena, const LorArenaConfig *config);
void lor_arena_deinit(LorArena *arena);
void lor_arena_reset(LorArena *arena);

int lor_arena_mark(LorArena *arena);
void lor_arena_rewind(LorArena *arena);

void *lor_arena_alloc(LorArena *arena, size_t size);
void *lor_arena_alloc_zero(LorArena *arena, size_t size);

void *lor_arena_alloc_array(LorArena *arena, size_t count, size_t elem_size);
void *lor_arena_alloc_array_zero(LorArena *arena, size_t count, size_t elem_size);

char *lor_arena_strdup(LorArena *arena, const char *text);

size_t lor_arena_used(const LorArena *arena);
size_t lor_arena_capacity(const LorArena *arena);
size_t lor_arena_committed(const LorArena *arena);

LorScratch lor_scratch_begin(LorArena **conflicts, size_t conflict_count);
void lor_scratch_end(LorScratch scratch);
void lor_scratch_cleanup_current_thread(void);

size_t lor_page_size(void);

typedef enum LorMmapMode {
    LOR_MMAP_READ = 0,
    LOR_MMAP_COPY = 1,
    LOR_MMAP_SHARED = 2
} LorMmapMode;

typedef struct LorMmap {
    void *data;
    size_t size;
} LorMmap;

LorMmap lor_mmap_file(const char *path, LorMmapMode mode);
void lor_mmap_unmap(LorMmap *map);

typedef struct LorLeakStats {
    size_t heap_count;
    size_t heap_bytes;
    size_t arena_count;
    size_t mmap_count;
    size_t mmap_bytes;
} LorLeakStats;

LorLeakStats lor_leakcheck_stats(void);
size_t lor_leakcheck_count(void);
size_t lor_leakcheck_report(FILE *out);

#if defined(LOR_LEAKCHECK)
void *lor_malloc_debug(size_t size, const char *file, int line);
void *lor_calloc_debug(size_t count, size_t elem_size, const char *file, int line);
void *lor_realloc_debug(void *ptr, size_t size, const char *file, int line);
void lor_free_debug(void *ptr, const char *file, int line);
char *lor_strdup_debug(const char *text, const char *file, int line);
void lor_arena_init_debug(LorArena *arena, size_t block_size, const char *file,
                          int line);
int lor_arena_init_ex_debug(LorArena *arena, const LorArenaConfig *config,
                            const char *file, int line);
LorMmap lor_mmap_file_debug(const char *path, LorMmapMode mode, const char *file,
                            int line);
#endif

#if defined(__GNUC__) || defined(__clang__)
#define LOR_CLEANUP_SUPPORTED 1
#define LOR_CLEANUP(fn) __attribute__((cleanup(fn)))
#else
#define LOR_CLEANUP_SUPPORTED 0
#define LOR_CLEANUP(fn)
#endif

static inline void lor_memory_cleanup_free_(void *ptr) {
    void **value = (void **)ptr;
    if (value == NULL || *value == NULL) { return; }
#if defined(LOR_LEAKCHECK)
    lor_free_debug(*value, NULL, 0);
#else
    free(*value);
#endif
    *value = NULL;
}

static inline void lor_memory_cleanup_arena_(void *arena) {
    lor_arena_deinit((LorArena *)arena);
}

static inline void lor_memory_cleanup_scratch_(void *scratch) {
    LorScratch *value = (LorScratch *)scratch;
    if (value == NULL || value->arena == NULL) { return; }
    lor_scratch_end(*value);
    value->arena = NULL;
}

static inline void lor_memory_cleanup_mmap_(void *map) {
    lor_mmap_unmap((LorMmap *)map);
}

static inline void lor_memory_cleanup_file_(void *file) {
    FILE **value = (FILE **)file;
    if (value == NULL || *value == NULL) { return; }
    (void)fclose(*value);
    *value = NULL;
}

#define LOR_AUTO_FREE LOR_CLEANUP(lor_memory_cleanup_free_)
#define LOR_AUTO_ARENA LOR_CLEANUP(lor_memory_cleanup_arena_)
#define LOR_AUTO_SCRATCH LOR_CLEANUP(lor_memory_cleanup_scratch_)
#define LOR_AUTO_MMAP LOR_CLEANUP(lor_memory_cleanup_mmap_)
#define LOR_AUTO_FILE LOR_CLEANUP(lor_memory_cleanup_file_)

#ifdef __cplusplus
}
#endif

/* Leakcheck build mode. Define LOR_LEAKCHECK for the whole build to route
   liblor memory calls and standard heap calls through location-aware tracking. */
#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_LOCATION_MACROS) && \
    !defined(LOR_SINGLE_HEADER_BUILD)
#define lor_arena_init(arena, block_size) \
    lor_arena_init_debug((arena), (block_size), __FILE__, __LINE__)
#define lor_arena_init_ex(arena, config) \
    lor_arena_init_ex_debug((arena), (config), __FILE__, __LINE__)
#define lor_mmap_file(path, mode) lor_mmap_file_debug((path), (mode), __FILE__, __LINE__)
#endif

#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_STDLIB_MACROS) && \
    !defined(LOR_SINGLE_HEADER_BUILD)
#define malloc(size) lor_malloc_debug((size), __FILE__, __LINE__)
#define calloc(count, elem_size) \
    lor_calloc_debug((count), (elem_size), __FILE__, __LINE__)
#define realloc(ptr, size) lor_realloc_debug((ptr), (size), __FILE__, __LINE__)
#define free(ptr) lor_free_debug((ptr), __FILE__, __LINE__)
#define strdup(text) lor_strdup_debug((text), __FILE__, __LINE__)
#endif
#endif
#ifdef LOR_IMPLEMENTATION

/* === memory: implementation === */
#ifdef LOR_ENABLE_MEMORY
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#else
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#include <stdalign.h>
#define LOR_ARENA_MAX_ALIGNMENT alignof(max_align_t)
#else
#define LOR_ARENA_MAX_ALIGNMENT \
    (sizeof(void *) > sizeof(double) ? sizeof(void *) : sizeof(double))
#endif

#if defined(_MSC_VER)
#define LOR_THREAD_LOCAL __declspec(thread)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define LOR_THREAD_LOCAL _Thread_local
#elif defined(__GNUC__) || defined(__clang__)
#define LOR_THREAD_LOCAL __thread
#else
#define LOR_THREAD_LOCAL
#endif

typedef enum LorLeakKind {
    LOR_LEAK_KIND_HEAP,
    LOR_LEAK_KIND_ARENA,
    LOR_LEAK_KIND_MMAP
} LorLeakKind;

#if defined(LOR_LEAKCHECK)
typedef struct LorLeakRecord LorLeakRecord;

struct LorLeakRecord {
    LorLeakRecord *next;
    LorLeakRecord *prev;
    LorLeakKind kind;
    void *ptr;
    size_t size;
    const char *file;
    int line;
};
#endif

struct LorArenaBlock {
    LorArenaBlock *next;
    size_t capacity;
    size_t committed;
    size_t used;
    size_t allocation_size;
    unsigned char data[];
};

struct LorArenaScope {
    LorArenaScope *prev;
    LorArenaBlock *block;
    size_t used;
};

#if defined(LOR_LEAKCHECK)
static LorLeakRecord *lor_memory__leaks = NULL;
#endif
static LOR_THREAD_LOCAL LorArena lor_memory__scratch_arenas[2];
static LOR_THREAD_LOCAL int lor_memory__scratch_inited[2];

static void *lor_memory__raw_malloc(size_t size) {
    return malloc(size);
}

#if defined(LOR_LEAKCHECK)
static void *lor_memory__raw_calloc(size_t count, size_t elem_size) {
    return calloc(count, elem_size);
}

static void *lor_memory__raw_realloc(void *ptr, size_t size) {
    return realloc(ptr, size);
}
#endif

static void lor_memory__raw_free(void *ptr) {
    free(ptr);
}

static int lor_memory__add_overflows_size(size_t a, size_t b) {
    return a > SIZE_MAX - b;
}

static int lor_memory__mul_overflows_size(size_t a, size_t b) {
    return b != 0 && a > SIZE_MAX / b;
}

static int lor_memory__is_power_of_two(size_t value) {
    return value != 0 && (value & (value - 1u)) == 0;
}

static size_t lor_memory__align_up(size_t value, size_t alignment) {
    size_t mask = alignment - 1u;
    return (value + mask) & ~mask;
}

static int lor_memory__align_forward(uintptr_t value, size_t alignment,
                                     uintptr_t *out) {
    uintptr_t mask = (uintptr_t)(alignment - 1u);

    if (value > UINTPTR_MAX - mask) { return 0; }

    *out = (value + mask) & ~mask;
    return 1;
}

#if defined(LOR_LEAKCHECK)
static void lor_leak__insert(LorLeakRecord *record) {
    record->prev = NULL;
    record->next = lor_memory__leaks;
    if (lor_memory__leaks != NULL) { lor_memory__leaks->prev = record; }
    lor_memory__leaks = record;
}

static void lor_leak__remove(LorLeakRecord *record) {
    if (record->prev != NULL) {
        record->prev->next = record->next;
    } else {
        lor_memory__leaks = record->next;
    }

    if (record->next != NULL) { record->next->prev = record->prev; }

    lor_memory__raw_free(record);
}

static LorLeakRecord *lor_leak__find(void *ptr, LorLeakKind kind) {
    LorLeakRecord *record = NULL;

    for (record = lor_memory__leaks; record != NULL; record = record->next) {
        if (record->ptr == ptr && record->kind == kind) { return record; }
    }

    return NULL;
}

static void lor_leak__track(LorLeakKind kind, void *ptr, size_t size,
                            const char *file, int line) {
    LorLeakRecord *record = NULL;

    if (ptr == NULL) { return; }

    record = (LorLeakRecord *)lor_memory__raw_malloc(sizeof(*record));
    if (record == NULL) { return; }

    record->kind = kind;
    record->ptr = ptr;
    record->size = size;
    record->file = file;
    record->line = line;
    lor_leak__insert(record);
}

static void lor_leak__untrack(LorLeakKind kind, void *ptr) {
    LorLeakRecord *record = lor_leak__find(ptr, kind);
    if (record != NULL) { lor_leak__remove(record); }
}

static const char *lor_leak__kind_name(LorLeakKind kind) {
    switch (kind) {
    case LOR_LEAK_KIND_HEAP: return "heap";
    case LOR_LEAK_KIND_ARENA: return "arena";
    case LOR_LEAK_KIND_MMAP: return "mmap";
    }

    return "unknown";
}
#else
#define lor_leak__track(kind, ptr, size, file, line) ((void)0)
#define lor_leak__untrack(kind, ptr) ((void)0)
#endif

LorLeakStats lor_leakcheck_stats(void) {
    LorLeakStats stats = {0};
#if defined(LOR_LEAKCHECK)
    LorLeakRecord *record = NULL;

    for (record = lor_memory__leaks; record != NULL; record = record->next) {
        switch (record->kind) {
        case LOR_LEAK_KIND_HEAP:
            stats.heap_count += 1u;
            stats.heap_bytes += record->size;
            break;
        case LOR_LEAK_KIND_ARENA:
            stats.arena_count += 1u;
            break;
        case LOR_LEAK_KIND_MMAP:
            stats.mmap_count += 1u;
            stats.mmap_bytes += record->size;
            break;
        }
    }
#endif

    return stats;
}

size_t lor_leakcheck_count(void) {
    LorLeakStats stats = lor_leakcheck_stats();
    return stats.heap_count + stats.arena_count + stats.mmap_count;
}

size_t lor_leakcheck_report(FILE *out) {
    size_t count = 0;
#if defined(LOR_LEAKCHECK)
    LorLeakRecord *record = NULL;

    if (out == NULL) { out = stderr; }

    for (record = lor_memory__leaks; record != NULL; record = record->next) {
        const char *file = record->file != NULL ? record->file : "?";
        fprintf(out, "LEAK %s: %zu bytes at %p (%s:%d)\n",
                lor_leak__kind_name(record->kind), record->size, record->ptr,
                file, record->line);
        count += 1u;
    }
#else
    (void)out;
#endif

    return count;
}

#if defined(LOR_LEAKCHECK)
void *lor_malloc_debug(size_t size, const char *file, int line) {
    void *ptr = NULL;

    if (size == 0) { return NULL; }

    ptr = lor_memory__raw_malloc(size);
    lor_leak__track(LOR_LEAK_KIND_HEAP, ptr, size, file, line);
    return ptr;
}

void *lor_calloc_debug(size_t count, size_t elem_size, const char *file,
                       int line) {
    void *ptr = NULL;

    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size)) {
        return NULL;
    }

    ptr = lor_memory__raw_calloc(count, elem_size);
    lor_leak__track(LOR_LEAK_KIND_HEAP, ptr, count * elem_size, file, line);
    return ptr;
}

void lor_free_debug(void *ptr, const char *file, int line) {
    (void)file;
    (void)line;

    if (ptr == NULL) { return; }

    lor_leak__untrack(LOR_LEAK_KIND_HEAP, ptr);
    lor_memory__raw_free(ptr);
}

void *lor_realloc_debug(void *ptr, size_t size, const char *file, int line) {
    LorLeakRecord *record = NULL;
    void *new_ptr = NULL;

    if (ptr == NULL) { return lor_malloc_debug(size, file, line); }

    if (size == 0) {
        lor_free_debug(ptr, file, line);
        return NULL;
    }

    record = lor_leak__find(ptr, LOR_LEAK_KIND_HEAP);
    new_ptr = lor_memory__raw_realloc(ptr, size);
    if (new_ptr == NULL) { return NULL; }

    if (record != NULL) {
        record->ptr = new_ptr;
        record->size = size;
        record->file = file;
        record->line = line;
    } else {
        lor_leak__track(LOR_LEAK_KIND_HEAP, new_ptr, size, file, line);
    }

    return new_ptr;
}

char *lor_strdup_debug(const char *text, const char *file, int line) {
    size_t len = 0;
    char *copy = NULL;

    if (text == NULL) { return NULL; }

    len = strlen(text);
    if (len == SIZE_MAX) { return NULL; }

    copy = (char *)lor_malloc_debug(len + 1u, file, line);
    if (copy == NULL) { return NULL; }

    memcpy(copy, text, len + 1u);
    return copy;
}
#endif

size_t lor_page_size(void) {
#if defined(_WIN32)
    SYSTEM_INFO info;
    GetSystemInfo(&info);
    return (size_t)info.dwPageSize;
#else
    long page_size = sysconf(_SC_PAGESIZE);
    if (page_size <= 0) { return LOR_KIB(4); }
    return (size_t)page_size;
#endif
}

static size_t lor_virtual__page_align(size_t size) {
    size_t page_size = lor_page_size();
    if (page_size == 0) { return size; }
    if (lor_memory__add_overflows_size(size, page_size - 1u)) { return 0; }
    return lor_memory__align_up(size, page_size);
}

static void *lor_virtual__reserve_raw(size_t size) {
#if defined(_WIN32)
    return VirtualAlloc(NULL, size, MEM_RESERVE, PAGE_READWRITE);
#else
    void *ptr = mmap(NULL, size, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    return ptr == MAP_FAILED ? NULL : ptr;
#endif
}

static int lor_virtual__commit_raw(void *ptr, size_t size) {
#if defined(_WIN32)
    return VirtualAlloc(ptr, size, MEM_COMMIT, PAGE_READWRITE) != NULL;
#else
    return mprotect(ptr, size, PROT_READ | PROT_WRITE) == 0;
#endif
}

static void lor_virtual__release_raw(void *ptr, size_t size) {
#if defined(_WIN32)
    (void)size;
    (void)VirtualFree(ptr, 0, MEM_RELEASE);
#else
    (void)munmap(ptr, size);
#endif
}

static size_t lor_arena__defaulted_block_size(size_t block_size) {
    return block_size != 0 ? block_size : LOR_ARENA_DEFAULT_BLOCK_SIZE;
}

static size_t lor_arena__defaulted_reserve_size(size_t reserve_size) {
    return reserve_size != 0 ? reserve_size : LOR_ARENA_DEFAULT_RESERVE_SIZE;
}

static size_t lor_arena__defaulted_commit_size(size_t commit_size) {
    return commit_size != 0 ? commit_size : LOR_ARENA_DEFAULT_COMMIT_SIZE;
}

static unsigned char *lor_arena__block_data(LorArenaBlock *block) {
    uintptr_t aligned = 0;

    if (!lor_memory__align_forward((uintptr_t)block->data,
                                   LOR_ARENA_MAX_ALIGNMENT, &aligned)) {
        return NULL;
    }

    return (unsigned char *)aligned;
}

static size_t lor_arena__block_header_slack(void) {
    return offsetof(LorArenaBlock, data) + LOR_ARENA_MAX_ALIGNMENT - 1u;
}

static LorArenaBlock *lor_arena__heap_block_new(size_t capacity) {
    size_t allocation_size = 0;
    LorArenaBlock *block = NULL;
    size_t slack = lor_arena__block_header_slack();

    if (lor_memory__add_overflows_size(capacity, slack)) { return NULL; }

    allocation_size = capacity + slack;
    block = (LorArenaBlock *)lor_memory__raw_malloc(allocation_size);
    if (block == NULL) { return NULL; }

    block->next = NULL;
    block->capacity = capacity;
    block->committed = capacity;
    block->used = 0;
    block->allocation_size = allocation_size;
    return block;
}

static LorArenaBlock *lor_arena__virtual_block_new(size_t reserve_size,
                                                   size_t commit_size,
                                                   size_t min_capacity) {
    size_t slack = lor_arena__block_header_slack();
    size_t min_reserve = 0;
    size_t data_offset = 0;
    LorArenaBlock *block = NULL;
    unsigned char *base = NULL;
    unsigned char *data = NULL;

    if (lor_memory__add_overflows_size(min_capacity, slack)) { return NULL; }

    min_reserve = min_capacity + slack;
    if (reserve_size < min_reserve) { reserve_size = min_reserve; }
    reserve_size = lor_virtual__page_align(reserve_size);
    if (reserve_size == 0) { return NULL; }

    if (commit_size < slack) { commit_size = slack; }
    if (commit_size < min_reserve && min_reserve < LOR_ARENA_DEFAULT_COMMIT_SIZE) {
        commit_size = min_reserve;
    }
    commit_size = lor_virtual__page_align(commit_size);
    if (commit_size > reserve_size) { commit_size = reserve_size; }

    block = (LorArenaBlock *)lor_virtual__reserve_raw(reserve_size);
    if (block == NULL) { return NULL; }
    if (commit_size != 0 && !lor_virtual__commit_raw(block, commit_size)) {
        lor_virtual__release_raw(block, reserve_size);
        return NULL;
    }

    block->next = NULL;
    block->capacity = 0;
    block->committed = commit_size;
    block->used = 0;
    block->allocation_size = reserve_size;

    base = (unsigned char *)block;
    data = lor_arena__block_data(block);
    if (data == NULL) {
        lor_virtual__release_raw(block, reserve_size);
        return NULL;
    }

    data_offset = (size_t)(data - base);
    block->capacity = reserve_size - data_offset;
    return block;
}

static void lor_arena__block_free(LorArena *arena, LorArenaBlock *block) {
    if (block == NULL) { return; }

    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
        lor_virtual__release_raw(block, block->allocation_size);
    } else {
        lor_memory__raw_free(block);
    }
}

static int lor_arena__block_ensure_committed(LorArenaBlock *block,
                                             size_t needed_used,
                                             size_t commit_size) {
    unsigned char *base = lor_arena__block_data(block);
    unsigned char *block_base = (unsigned char *)block;
    size_t data_offset = 0;
    size_t needed_total = 0;
    size_t new_committed = 0;

    if (base == NULL || needed_used > block->capacity) { return 0; }

    data_offset = (size_t)(base - block_base);
    if (lor_memory__add_overflows_size(data_offset, needed_used)) { return 0; }
    needed_total = data_offset + needed_used;

    if (needed_total <= block->committed) { return 1; }

    new_committed = needed_total;
    if (commit_size != 0) {
        if (lor_memory__add_overflows_size(new_committed, commit_size - 1u)) {
            return 0;
        }
        new_committed = lor_memory__align_up(new_committed, commit_size);
    }

    if (new_committed > block->allocation_size) {
        new_committed = block->allocation_size;
    }
    if (!lor_virtual__commit_raw(block_base + block->committed,
                                 new_committed - block->committed)) {
        return 0;
    }

    block->committed = new_committed;
    return 1;
}

static void *lor_arena__block_alloc(LorArena *arena, LorArenaBlock *block,
                                    size_t size, size_t alignment) {
    unsigned char *base = lor_arena__block_data(block);
    uintptr_t current = 0;
    uintptr_t aligned = 0;
    size_t padding = 0;
    size_t new_used = 0;

    if (base == NULL || block->used > block->capacity) { return NULL; }

    current = (uintptr_t)(base + block->used);
    if (!lor_memory__align_forward(current, alignment, &aligned)) { return NULL; }

    padding = (size_t)(aligned - current);
    if (padding > block->capacity - block->used) { return NULL; }
    if (size > block->capacity - block->used - padding) { return NULL; }

    new_used = block->used + padding + size;
    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL &&
        !lor_arena__block_ensure_committed(block, new_used, arena->commit_size)) {
        return NULL;
    }

    block->used = new_used;
    return (void *)aligned;
}

static LorArenaBlock *lor_arena__block_new(LorArena *arena, size_t min_capacity) {
    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
        return lor_arena__virtual_block_new(arena->reserve_size, arena->commit_size,
                                            min_capacity);
    }

    if (arena->block_size < min_capacity) { return lor_arena__heap_block_new(min_capacity); }
    return lor_arena__heap_block_new(arena->block_size);
}

static int lor_arena__init_internal(LorArena *arena, const LorArenaConfig *config,
                                    int track_leakcheck, const char *file,
                                    int line) {
    LorArenaConfig defaults = {0};
#if !defined(LOR_LEAKCHECK)
    (void)file;
    (void)line;
#endif

    if (arena == NULL) { return 0; }

    if (config == NULL) { config = &defaults; }

    arena->blocks = NULL;
    arena->scopes = NULL;
    arena->backend = config->backend;
    arena->block_size = lor_arena__defaulted_block_size(config->block_size);
    arena->reserve_size = lor_arena__defaulted_reserve_size(config->reserve_size);
    arena->commit_size = lor_arena__defaulted_commit_size(config->commit_size);

    if (arena->backend != LOR_ARENA_BACKEND_HEAP &&
        arena->backend != LOR_ARENA_BACKEND_VIRTUAL) {
        *arena = (LorArena)LOR_ARENA_INIT;
        return 0;
    }

    if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
        arena->reserve_size = lor_virtual__page_align(arena->reserve_size);
        arena->commit_size = lor_virtual__page_align(arena->commit_size);
        if (arena->reserve_size == 0 || arena->commit_size == 0) {
            *arena = (LorArena)LOR_ARENA_INIT;
            return 0;
        }
    }

    if (track_leakcheck) { lor_leak__track(LOR_LEAK_KIND_ARENA, arena, 0, file, line); }

    return 1;
}

static void lor_arena__init_at(LorArena *arena, size_t block_size,
                               const char *file, int line) {
    LorArenaConfig config = {0};
    config.backend = LOR_ARENA_BACKEND_HEAP;
    config.block_size = block_size;
    (void)lor_arena__init_internal(arena, &config, 1, file, line);
}

#if defined(LOR_LEAKCHECK)
void lor_arena_init_debug(LorArena *arena, size_t block_size, const char *file,
                          int line) {
    lor_arena__init_at(arena, block_size, file, line);
}
#endif

void lor_arena_init(LorArena *arena, size_t block_size) {
    lor_arena__init_at(arena, block_size, NULL, 0);
}

#if defined(LOR_LEAKCHECK)
int lor_arena_init_ex_debug(LorArena *arena, const LorArenaConfig *config,
                            const char *file, int line) {
    return lor_arena__init_internal(arena, config, 1, file, line);
}
#endif

int lor_arena_init_ex(LorArena *arena, const LorArenaConfig *config) {
    return lor_arena__init_internal(arena, config, 1, NULL, 0);
}

void lor_arena_deinit(LorArena *arena) {
    LorArenaBlock *block = NULL;
    LorArenaScope *scope = NULL;

    if (arena == NULL) { return; }

    scope = arena->scopes;
    while (scope != NULL) {
        LorArenaScope *prev = scope->prev;
        lor_memory__raw_free(scope);
        scope = prev;
    }

    block = arena->blocks;
    while (block != NULL) {
        LorArenaBlock *next = block->next;
        lor_arena__block_free(arena, block);
        block = next;
    }

    lor_leak__untrack(LOR_LEAK_KIND_ARENA, arena);

    *arena = (LorArena)LOR_ARENA_INIT;
}

void lor_arena_reset(LorArena *arena) {
    LorArenaBlock *block = NULL;
    LorArenaScope *scope = NULL;

    if (arena == NULL) { return; }

    scope = arena->scopes;
    while (scope != NULL) {
        LorArenaScope *prev = scope->prev;
        lor_memory__raw_free(scope);
        scope = prev;
    }
    arena->scopes = NULL;

    for (block = arena->blocks; block != NULL; block = block->next) {
        block->used = 0;
    }
}

int lor_arena_mark(LorArena *arena) {
    LorArenaScope *scope = NULL;

    if (arena == NULL) { return 0; }

    scope = (LorArenaScope *)lor_memory__raw_malloc(sizeof(*scope));
    if (scope == NULL) { return 0; }

    scope->block = arena->blocks;
    scope->used = arena->blocks != NULL ? arena->blocks->used : 0;
    scope->prev = arena->scopes;
    arena->scopes = scope;
    return 1;
}

static void lor_arena__rewind_to(LorArena *arena, LorArenaBlock *mark_block,
                                 size_t mark_used) {
    LorArenaBlock *block = NULL;

    if (arena == NULL) { return; }

    if (mark_block == NULL) {
        for (block = arena->blocks; block != NULL; block = block->next) {
            block->used = 0;
        }
        return;
    }

    while (arena->blocks != NULL && arena->blocks != mark_block) {
        block = arena->blocks;
        arena->blocks = block->next;
        lor_arena__block_free(arena, block);
    }

    if (arena->blocks != NULL) {
        if (mark_used <= arena->blocks->used) { arena->blocks->used = mark_used; }
    }
}

void lor_arena_rewind(LorArena *arena) {
    LorArenaScope *scope = NULL;

    if (arena == NULL || arena->scopes == NULL) { return; }

    scope = arena->scopes;
    arena->scopes = scope->prev;
    lor_arena__rewind_to(arena, scope->block, scope->used);
    lor_memory__raw_free(scope);
}

static void *lor_arena__alloc_aligned(LorArena *arena, size_t size,
                                      size_t alignment) {
    size_t min_capacity = 0;
    LorArenaBlock *block = NULL;
    void *result = NULL;

    if (arena == NULL || size == 0 || !lor_memory__is_power_of_two(alignment)) {
        return NULL;
    }

    if (arena->block_size == 0 && arena->reserve_size == 0) {
        lor_arena_init(arena, 0);
    }

    if (arena->blocks != NULL) {
        result = lor_arena__block_alloc(arena, arena->blocks, size, alignment);
        if (result != NULL) { return result; }
    }

    min_capacity = size;
    if (alignment > 1u) {
        if (lor_memory__add_overflows_size(min_capacity, alignment - 1u)) {
            return NULL;
        }
        min_capacity += alignment - 1u;
    }

    block = lor_arena__block_new(arena, min_capacity);
    if (block == NULL) { return NULL; }

    block->next = arena->blocks;
    arena->blocks = block;
    return lor_arena__block_alloc(arena, block, size, alignment);
}

void *lor_arena_alloc(LorArena *arena, size_t size) {
    return lor_arena__alloc_aligned(arena, size, LOR_ARENA_MAX_ALIGNMENT);
}

void *lor_arena_alloc_zero(LorArena *arena, size_t size) {
    void *ptr = lor_arena_alloc(arena, size);

    if (ptr != NULL) { memset(ptr, 0, size); }

    return ptr;
}

void *lor_arena_alloc_array(LorArena *arena, size_t count, size_t elem_size) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size)) {
        return NULL;
    }

    return lor_arena_alloc(arena, count * elem_size);
}

void *lor_arena_alloc_array_zero(LorArena *arena, size_t count, size_t elem_size) {
    if (count == 0 || elem_size == 0 ||
        lor_memory__mul_overflows_size(count, elem_size)) {
        return NULL;
    }

    return lor_arena_alloc_zero(arena, count * elem_size);
}

char *lor_arena_strdup(LorArena *arena, const char *text) {
    size_t len = 0;
    char *copy = NULL;

    if (text == NULL) { return NULL; }

    len = strlen(text);
    if (len == SIZE_MAX) { return NULL; }

    copy = (char *)lor_arena_alloc(arena, len + 1u);
    if (copy == NULL) { return NULL; }

    memcpy(copy, text, len + 1u);
    return copy;
}

size_t lor_arena_used(const LorArena *arena) {
    size_t total = 0;
    const LorArenaBlock *block = NULL;

    if (arena == NULL) { return 0; }

    for (block = arena->blocks; block != NULL; block = block->next) {
        total += block->used;
    }

    return total;
}

size_t lor_arena_capacity(const LorArena *arena) {
    size_t total = 0;
    const LorArenaBlock *block = NULL;

    if (arena == NULL) { return 0; }

    for (block = arena->blocks; block != NULL; block = block->next) {
        total += block->capacity;
    }

    return total;
}

size_t lor_arena_committed(const LorArena *arena) {
    size_t total = 0;
    const LorArenaBlock *block = NULL;

    if (arena == NULL) { return 0; }

    for (block = arena->blocks; block != NULL; block = block->next) {
        if (arena->backend == LOR_ARENA_BACKEND_VIRTUAL) {
            unsigned char *base = (unsigned char *)block;
            unsigned char *data = lor_arena__block_data((LorArenaBlock *)block);
            size_t data_offset = data != NULL ? (size_t)(data - base) : 0;
            if (block->committed > data_offset) {
                total += block->committed - data_offset;
            }
        } else {
            total += block->committed;
        }
    }

    return total;
}

LorScratch lor_scratch_begin(LorArena **conflicts, size_t conflict_count) {
    size_t i = 0;
    size_t j = 0;

    for (i = 0; i < 2u; ++i) {
        int conflict = 0;

        for (j = 0; j < conflict_count; ++j) {
            if (conflicts != NULL && conflicts[j] == &lor_memory__scratch_arenas[i]) {
                conflict = 1;
                break;
            }
        }

        if (conflict) { continue; }

        if (!lor_memory__scratch_inited[i]) {
            LorArenaConfig config = {0};
            config.backend = LOR_ARENA_BACKEND_HEAP;
            config.block_size = LOR_ARENA_DEFAULT_BLOCK_SIZE;
            if (!lor_arena__init_internal(&lor_memory__scratch_arenas[i], &config,
                                          0, NULL, 0)) {
                return (LorScratch){0};
            }
            lor_memory__scratch_inited[i] = 1;
        }

        return (LorScratch){
            &lor_memory__scratch_arenas[i],
            lor_memory__scratch_arenas[i].blocks,
            lor_memory__scratch_arenas[i].blocks != NULL
                ? lor_memory__scratch_arenas[i].blocks->used
                : 0,
        };
    }

    return (LorScratch){0};
}

void lor_scratch_end(LorScratch scratch) {
    lor_arena__rewind_to(scratch.arena, scratch.block, scratch.used);
}

void lor_scratch_cleanup_current_thread(void) {
    size_t i = 0;

    for (i = 0; i < 2u; ++i) {
        if (lor_memory__scratch_inited[i]) {
            lor_arena_deinit(&lor_memory__scratch_arenas[i]);
            lor_memory__scratch_inited[i] = 0;
        }
    }
}

#if defined(_WIN32)
static DWORD lor_mmap__windows_protect(LorMmapMode mode) {
    switch (mode) {
    case LOR_MMAP_SHARED: return PAGE_READWRITE;
    case LOR_MMAP_COPY: return PAGE_WRITECOPY;
    case LOR_MMAP_READ: return PAGE_READONLY;
    }
    return PAGE_READONLY;
}

static DWORD lor_mmap__windows_access(LorMmapMode mode) {
    switch (mode) {
    case LOR_MMAP_SHARED: return FILE_MAP_WRITE;
    case LOR_MMAP_COPY: return FILE_MAP_COPY;
    case LOR_MMAP_READ: return FILE_MAP_READ;
    }
    return FILE_MAP_READ;
}
#endif

static LorMmap lor_mmap__file_at(const char *path, LorMmapMode mode,
                                 const char *file, int line) {
    LorMmap map = {0};
#if !defined(LOR_LEAKCHECK)
    (void)file;
    (void)line;
#endif

    if (path == NULL) { return map; }

#if defined(_WIN32)
    {
        DWORD access =
            mode == LOR_MMAP_SHARED ? GENERIC_READ | GENERIC_WRITE : GENERIC_READ;
        DWORD create = OPEN_EXISTING;
        LARGE_INTEGER file_size;
        HANDLE file = CreateFileA(path, access, FILE_SHARE_READ | FILE_SHARE_WRITE,
                                  NULL, create, FILE_ATTRIBUTE_NORMAL, NULL);
        HANDLE mapping = NULL;

        if (file == INVALID_HANDLE_VALUE) { return map; }
        if (!GetFileSizeEx(file, &file_size) || file_size.QuadPart <= 0) {
            CloseHandle(file);
            return map;
        }
        if ((uint64_t)file_size.QuadPart > SIZE_MAX) {
            CloseHandle(file);
            return map;
        }

        mapping = CreateFileMappingA(file, NULL, lor_mmap__windows_protect(mode),
                                     0, 0, NULL);
        CloseHandle(file);
        if (mapping == NULL) { return map; }

        map.data = MapViewOfFile(mapping, lor_mmap__windows_access(mode), 0, 0, 0);
        CloseHandle(mapping);
        if (map.data == NULL) { return (LorMmap){0}; }

        map.size = (size_t)file_size.QuadPart;
    }
#else
    {
        int flags = mode == LOR_MMAP_SHARED ? O_RDWR : O_RDONLY;
        int prot = PROT_READ;
        int mmap_flags = mode == LOR_MMAP_SHARED ? MAP_SHARED : MAP_PRIVATE;
        struct stat st;
        int fd = open(path, flags);

        if (fd < 0) { return map; }
        if (fstat(fd, &st) != 0 || st.st_size <= 0) {
            close(fd);
            return map;
        }
        if ((uint64_t)st.st_size > SIZE_MAX) {
            close(fd);
            return map;
        }

        if (mode != LOR_MMAP_READ) { prot |= PROT_WRITE; }

        map.size = (size_t)st.st_size;
        map.data = mmap(NULL, map.size, prot, mmap_flags, fd, 0);
        close(fd);
        if (map.data == MAP_FAILED) { return (LorMmap){0}; }
    }
#endif

    lor_leak__track(LOR_LEAK_KIND_MMAP, map.data, map.size, file, line);
    return map;
}

#if defined(LOR_LEAKCHECK)
LorMmap lor_mmap_file_debug(const char *path, LorMmapMode mode, const char *file,
                            int line) {
    return lor_mmap__file_at(path, mode, file, line);
}
#endif

LorMmap lor_mmap_file(const char *path, LorMmapMode mode) {
    return lor_mmap__file_at(path, mode, NULL, 0);
}

void lor_mmap_unmap(LorMmap *map) {
    if (map == NULL || map->data == NULL) { return; }

    lor_leak__untrack(LOR_LEAK_KIND_MMAP, map->data);

#if defined(_WIN32)
    (void)UnmapViewOfFile(map->data);
#else
    (void)munmap(map->data, map->size);
#endif

    map->data = NULL;
    map->size = 0;
}
#endif

#endif
/* Optional short-name aliases
   These are preprocessor aliases only. They do not change compiled
   symbol names unless LOR_CUSTOM_PREFIX is also used. */
#ifdef LOR_STRIP_PREFIX
#ifdef LOR_ENABLE_MEMORY
#define ArenaBackend LorArenaBackend
#define ArenaConfig LorArenaConfig
#define Arena LorArena
#define ArenaBlock LorArenaBlock
#define ArenaScope LorArenaScope
#define Scratch LorScratch
#define MmapMode LorMmapMode
#define Mmap LorMmap
#define LeakStats LorLeakStats
#define KIB LOR_KIB
#define MIB LOR_MIB
#define GIB LOR_GIB
#define ARENA_BACKEND_HEAP LOR_ARENA_BACKEND_HEAP
#define ARENA_BACKEND_VIRTUAL LOR_ARENA_BACKEND_VIRTUAL
#define ARENA_DEFAULT_BLOCK_SIZE LOR_ARENA_DEFAULT_BLOCK_SIZE
#define ARENA_DEFAULT_RESERVE_SIZE LOR_ARENA_DEFAULT_RESERVE_SIZE
#define ARENA_DEFAULT_COMMIT_SIZE LOR_ARENA_DEFAULT_COMMIT_SIZE
#define ARENA_INIT LOR_ARENA_INIT
#define MMAP_READ LOR_MMAP_READ
#define MMAP_COPY LOR_MMAP_COPY
#define MMAP_SHARED LOR_MMAP_SHARED
#define CLEANUP_SUPPORTED LOR_CLEANUP_SUPPORTED
#define CLEANUP LOR_CLEANUP
#define AUTO_FREE LOR_AUTO_FREE
#define AUTO_ARENA LOR_AUTO_ARENA
#define AUTO_SCRATCH LOR_AUTO_SCRATCH
#define AUTO_MMAP LOR_AUTO_MMAP
#define AUTO_FILE LOR_AUTO_FILE
#define arena_init lor_arena_init
#define arena_init_ex lor_arena_init_ex
#define arena_deinit lor_arena_deinit
#define arena_reset lor_arena_reset
#define arena_mark lor_arena_mark
#define arena_rewind lor_arena_rewind
#define arena_alloc lor_arena_alloc
#define arena_alloc_zero lor_arena_alloc_zero
#define arena_alloc_array lor_arena_alloc_array
#define arena_alloc_array_zero lor_arena_alloc_array_zero
#define arena_strdup lor_arena_strdup
#define arena_used lor_arena_used
#define arena_capacity lor_arena_capacity
#define arena_committed lor_arena_committed
#define scratch_begin lor_scratch_begin
#define scratch_end lor_scratch_end
#define scratch_cleanup_current_thread lor_scratch_cleanup_current_thread
#define page_size lor_page_size
#define mmap_file lor_mmap_file
#define mmap_unmap lor_mmap_unmap
#define leakcheck_stats lor_leakcheck_stats
#define leakcheck_count lor_leakcheck_count
#define leakcheck_report lor_leakcheck_report
#endif
#endif

#undef LOR_SINGLE_HEADER_BUILD
/* Leakcheck build mode
   Define LOR_LEAKCHECK for the whole build to route liblor memory
   calls and stdlib heap calls through location-aware tracking. */
#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_LOCATION_MACROS)
#define lor_arena_init(arena, block_size) \
    lor_arena_init_debug((arena), (block_size), __FILE__, __LINE__)
#define lor_arena_init_ex(arena, config) \
    lor_arena_init_ex_debug((arena), (config), __FILE__, __LINE__)
#define lor_mmap_file(path, mode) \
    lor_mmap_file_debug((path), (mode), __FILE__, __LINE__)
#endif

#if defined(LOR_LEAKCHECK) && !defined(LOR_MEMORY_NO_STDLIB_MACROS)
#define malloc(size) lor_malloc_debug((size), __FILE__, __LINE__)
#define calloc(count, elem_size) \
    lor_calloc_debug((count), (elem_size), __FILE__, __LINE__)
#define realloc(ptr, size) lor_realloc_debug((ptr), (size), __FILE__, __LINE__)
#define free(ptr) lor_free_debug((ptr), __FILE__, __LINE__)
#define strdup(text) lor_strdup_debug((text), __FILE__, __LINE__)
#endif

#endif /* LOR_SINGLE_HEADER_H */
