main: main.c
	clang -Wall -Wextra -I$(HOME)/opt/libmill/include/ -o main main.c -L$(HOME)/opt/libmill/lib/ -l:libmill.a

server: server.c
	clang -Wall -Wextra -I$(HOME)/opt/libmill/include/ -o server server.c -L$(HOME)/opt/libmill/lib/ -l:libmill.a

