#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "tools" / "lor_modules.json"


def public_functions(manifest: Path) -> list[str]:
    data = json.loads(manifest.read_text(encoding="utf-8"))
    functions = []
    seen = set()

    for module in data["modules"]:
        for canonical, _alias in module.get("symbols", {}).get("functions", []):
            if canonical not in seen:
                functions.append(canonical)
                seen.add(canonical)

    return functions


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Windows module-definition file for liblor."
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    lines = [
        "; Generated by tools/gen_exports.py. Do not edit.",
        "LIBRARY lor",
        "EXPORTS",
    ]
    lines.extend(f"    {name}" for name in public_functions(args.manifest))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
